### ISSUE TITLE
Disable all folder stuff?

### ISSUE THREAD

**Issue by parker789** [crazy-max/docker-rtorrent-rutorrent#103]
Hey there, I love the work and have been directed here by linuxservers rutorrent build, so that's saying something!

Anyways, I have a very simple setup where I manually add each torrent through the rutorrent interface, as well as manually set the correct download location. Since moving my session information from linuxservers docker instance to yours I've noticed a lot of duplicate files have been created within /downloads/incoming, etc. Is there a way I can completely disable all of these automated niceties in favor of my brute force manual approach?

My preferred approach would be this:

1. Pass /config directory as a volume to the container
2. Pass a /downloads directory as a volume to the container, where this is the "filesystem" than can be viewed within rutorrent when choosing a save path after adding a new torrent. I'd then add a torrent, select whichever subfolder within /downloads to save the torrent data to, and off I'd go. 

Thanks

**Comment by JoshTheBlack** [comment]
See here: https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/44

I didn't like having the temp and complete folders auto-created in my mounted space, so I mounted it to /downloads/fs/
Then I mounted a subdirectory of my mounted space as /downloads so it could create the two folders somewhere less problematic.  

Also, made the changes recommended in the above link.
