### ISSUE TITLE
symlinks to plugins.ini and access.ini missing

### ISSUE THREAD

**Issue by Znubbis** [crazy-max/docker-rtorrent-rutorrent#104]
### Behaviour
Symlinks to plugins.ini and access.ini for ru torrent does not seem to work right if you have the files in the data path.

#### Steps to reproduce this issue

Hello, I'm new to dockers so I might have done something wrong but it seems that these symlinks are not created if the data folder have content, like when rebuilding / reinstalling.
 
/data/rutorrent/conf/access.ini     and   /var/www/rutorrent/conf/access.ini
/data/rutorrent/conf/plugins.ini   and   /var/www/rutorrent/conf/plugins.ini 

The settings in ruTorrent works if I create these manually

Might it be that the ln -sf... part in the code below should be run regardless if the file is found or not?

Symlinking ruTorrent config
ln -sf /data/rutorrent/conf/users /var/www/rutorrent/conf/users
if [ ! -f /data/rutorrent/conf/access.ini ]; then
  echo "Symlinking ruTorrent access.ini file..."
  mv /var/www/rutorrent/conf/access.ini /data/rutorrent/conf/access.ini
  ln -sf /data/rutorrent/conf/access.ini /var/www/rutorrent/conf/access.ini
fi
chown rtorrent. /data/rutorrent/conf/access.ini
if [ ! -f /data/rutorrent/conf/plugins.ini ]; then
  echo "Symlinking ruTorrent plugins.ini file..."
  mv /var/www/rutorrent/conf/plugins.ini /data/rutorrent/conf/plugins.ini
  ln -sf /data/rutorrent/conf/plugins.ini /var/www/rutorrent/conf/plugins.ini
fi

### Configuration

* Docker version (type `docker --version`) :  20.10.7, build f0df350
* Docker compose version if applicable (type `docker-compose --version`) : 1.21.0, build unknown
* Platform (Debian 9, Ubuntu 18.04, ...) : Debian 10
* System info (type `uname -a`) : Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64 GNU/Linux

Thank you for all your work, I have had a great time trying to get it to work and I think it will be great if I solve the mentioned problem.

**Comment by crazy-max** [comment]
@Znubbis 

> does not seem to work

Can't tell without repro and logs. Please create a proper [bug report](https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/new?assignees=&labels=&template=bug.yml).
