### ISSUE TITLE
Save settings

### ISSUE THREAD

**Issue by FloydKulis** [crazy-max/docker-rtorrent-rutorrent#108]
Is it possible for the speed limit settings to be remembered even after restarting Docker?

**Comment by crazy-max** [comment]
Settings are already saved for ruTorrent in `/data/rutorrent/conf` and/or `/data/rutorrent/share/users`. If you don't think so please create a [bug report](https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/new?assignees=&labels=&template=bug.yml).
