### ISSUE TITLE
Enable https

### ISSUE THREAD

**Issue by drifter75** [crazy-max/docker-rtorrent-rutorrent#110]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Is it possible to enable https? 

### Expected behaviour

none

### Actual behaviour

none

### Steps to reproduce

none

### Docker info

```yaml
none
```

### Version

* Docker compose version (type `docker-compose --version`):
* System info (type `uname -a`):
none

### Docker compose

```yaml
none
```

### Container logs

none

**Comment by carlzoo** [comment]
take a look at the Traefik Example: https://github.com/crazy-max/docker-rtorrent-rutorrent/tree/master/examples/traefik
