### ISSUE TITLE
Auto-delete the torrent and data after 96h times, after finish download.

### ISSUE THREAD

**Issue by FloydKulis** [crazy-max/docker-rtorrent-rutorrent#111]
Does anyone know a solution how to make the data automatically deleted after e.g. 96 hours after downloading the torrent?

I found something like this:

> > Ratio Management
> While rTorrent has a built-in form of ratio management since a few versions, it’s hard to use after-the-fact and also hard to understand — you need to have different watch directories and complex settings in your .rtorrent.rc to use that.
> 
> It can be much simpler — a basic form of ratio management using rtcontrol looks like this:
> 
> rtcontrol is_complete=yes is_open=yes ratio=+1.1 alias=sometracker,othertracker --stop
> You will always want to have the is_complete=yes is_open=yes ratio=+1.1 part, which excludes all torrents that are still downloading, closed or not having the necessary ratio. Another basic filter is is_ignored=no, which excludes items that have their ignore commands flag set (via the I key) from ratio management.

Source:
https://pyrocore.readthedocs.io/en/latest/usage.html#deleting-download-items-and-their-data

**Comment by crazy-max** [comment]
https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md#closure-policy

Should be asked on upstream repos (either https://github.com/Novik/ruTorrent or https://github.com/rakshasa/rtorrent)
