### ISSUE TITLE
Question regarding hardlinking after download/move

### ISSUE THREAD

**Issue by chazaroo1980** [crazy-max/docker-rtorrent-rutorrent#112]
Could anyone tell me what im doing wrong with these commands. I have my files set to download to a specific location from there I want to hardlink them to another the folder it goes to is set by the rtorrent label where a uploader will pick them up and transfer to google for safe keeping while the originals seed. Ive managed to get it working for content within a folder but any files not in a folder dont get picked up.

method.insert = d.finished_dir, simple, "cat=/mnt/downloads/,$d.custom1="
method.set_key = event.download.finished,move_complete2,"execute=cp,-R,l,$d.data_path=,$d.finished_dir="

I had tried using auto tools. but it doesnt work at all it does nothing whatsoever on any configuration.

**Comment by crazy-max** [comment]
https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md#closure-policy

Should be asked on upstream repos (either https://github.com/Novik/ruTorrent or https://github.com/rakshasa/rtorrent)
