### ISSUE TITLE
Expose PUID/GUID options

### ISSUE THREAD

**Issue by elmerfdz** [crazy-max/docker-rtorrent-rutorrent#12]
Hi! is it possible to expose PUID/GUID options?

**Comment by crazy-max** [comment]
Hi @elmerfdz, I have plan to do this on this image soon. Already done for [my nextcloud docker image](https://github.com/crazy-max/docker-nextcloud) if you want to take a look at [the changes](https://github.com/crazy-max/docker-nextcloud/blob/master/CHANGELOG.md#1701-rc3--1606-rc3--15013-rc3-20191118).

**Comment by elmerfdz** [comment]
Great! looking forward to try it out.

**Comment by crazy-max** [comment]
Solved, see [CHANGELOG.md](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/CHANGELOG.md) for more info.

**Comment by elmerfdz** [comment]
Thanks! works as expected.
