### ISSUE TITLE
Errors appear in the logs after applying RU_REMOVE_CORE_PLUGINS

### ISSUE THREAD

**Issue by adamwinn** [crazy-max/docker-rtorrent-rutorrent#122]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I set `RU_REMOVE_CORE_PLUGINS` to `_cloudflare,_noty,_noty2,chunks,cookies,cpuload,create,diskspace,edit,extratio,extsearch,feeds,filedrop,geoip2,ipad,loginmgr,lookat,mediainfo,ratio,retrackers,rss,rssurlrewrite,rutracker_check,scheduler,screenshots,spectrogram,theme,xmpp`

In the logs, I now see

`/var/run/s6/etc/cont-init.d/03-config.sh: line 281: can't create /var/www/rutorrent/plugins/create/conf.php: nonexistent directory`

`chown: cannot access '/var/www/rutorrent/plugins/create/conf.php': No such file or directory`

`ln: failed to create symbolic link '/var/www/rutorrent/plugins/geoip2/database/GeoLite2-ASN.mmdb': No such file or directory`

`ln: failed to create symbolic link '/var/www/rutorrent/plugins/geoip2/database/GeoLite2-City.mmdb': No such file or directory`

`ln: failed to create symbolic link '/var/www/rutorrent/plugins/geoip2/database/GeoLite2-Country.mmdb': No such file or directory`

### Expected behaviour

Checks should be made so those errors dont appear when certain plugins are disabled

### Actual behaviour

Errors in the logs appear

### Steps to reproduce

1. Set `RU_REMOVE_CORE_PLUGINS` to `_cloudflare,_noty,_noty2,chunks,cookies,cpuload,create,diskspace,edit,extratio,extsearch,feeds,filedrop,geoip2,ipad,loginmgr,lookat,mediainfo,ratio,retrackers,rss,rssurlrewrite,rutracker_check,scheduler,screenshots,spectrogram,theme,xmpp`

2.  Start container

3. View errors in the log file

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 10
  Running: 9
  Paused: 0
  Stopped: 1
 Images: 7
 Server Version: 20.10.3
 Storage Driver: btrfs
  Build Version: Btrfs v4.0
  Library Version: 101
 Logging Driver: db
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs db fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea3508454ff2268c32720eb4d2fc9816d6f75f88
 runc version: 31cc25f16f5eba4d0f53e35374532873744f4b31
 init version: ed96d00 (expected: de40ad0)
 Security Options:
  apparmor
 Kernel Version: 4.4.180+
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.32GiB
 Name: DiskStation
 ID: TKJ6:OOPS:DLHP:LVJL:CDWA:JLVD:6O3A:OMQI:BHGE:VN4V:B7LE:JBLE
 Docker Root Dir: /volume3/@docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory TCP limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Version

docker-compose version 1.28.5, build 324b023a

Linux DiskStation 4.4.180+ #41890 SMP Thu Jul 15 03:42:45 CST 2021 x86_64 GNU/Linux synology_v1000_1821+

### Docker compose

```yaml
.
```

### Container logs

![Screen Shot 2021-09-14 at 12 12 51 AM](https://user-images.githubusercontent.com/3028964/133204816-bb9f4086-10a8-4656-bf8b-7b23fef32bf5.jpg)

**Comment by crazy-max** [comment]
@adamwinn Yeah we might need to skip checks for disabled plugins.
