### ISSUE TITLE
Removing Torrent Without Erasing Data

### ISSUE THREAD

**Issue by neo-neo1** [crazy-max/docker-rtorrent-rutorrent#129]
The way [.rtorrent.rc](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/rootfs/tpls/.rtorrent.rc) is setup it's impossible to delete torrent and keep the data. How do I disable this?

```
# Erase data when torrent deleted (no need erasedata plugin on ruTorrent)
method.set_key = event.download.erased,delete_erased,"execute=rm,-rf,--,$d.data_path="
```

 I need ability to remove torrents and retain data. Am I missing something?

**Comment by adamwinn** [comment]
Just delete that line

**Comment by crazy-max** [comment]
As @adamwinn says, remove this line in `/data/rtorrent/.rtorrent.rc`.

**Comment by pwinnski** [comment]
This absolutely does not work for me. I commented out the line, and then removed the line, and despite multiple restarts since, files disappear from the filesystem when the torrent is removed.
