### ISSUE TITLE
would you consider add irssi into this docker image?

### ISSUE THREAD

**Issue by xyou365** [crazy-max/docker-rtorrent-rutorrent#13]
Recently I am using your docker image and find that it is so wonderful. However there is no irssi inside. Would you consider add irssi into?

**Comment by whalehub** [comment]
@crazy-max Any thoughts on this?

**Comment by crazy-max** [comment]
@xyou365 Do you talk about https://irssi.org/ or https://github.com/autodl-community/autodl-irssi ?
Anyway, I prefer to keep this image as light as possible. I think in this case it would be better to have a dedicated Docker image for irssi that would communicate with this image through XMLRPC if possible.
