### ISSUE TITLE
opt-out WAN_IP env var

### ISSUE THREAD

**Issue by Ylawy** [crazy-max/docker-rtorrent-rutorrent#131]
Hi,

my IP changes every 24h. How does your container handle those ip changes? iI can see the .rtorrent.rc file has the following settings:
schedule2 = ip_tick,0,1800,ip=rakshasa
schedule2 = bind_tick,0,1800,bind=rakshasa
but it's not explained in the docs what they do. I enabled both but whenever my IP changes the previous IP is still set in Settings -> Bittorrent.

Thank you

**Comment by SeeTwoArrr** [comment]
I suspect you will have to restart the container. If I interpreted everything correctly it does a query on launch to get your public IP and then starts rtorrrent with that IP to publish to trackers.

You can set the IP address to publish to trackers in ruTorrent as well, but this is manual.

**Comment by Ylawy** [comment]
Thanks for your feedback but a restart every 24h is not a good way to go about it. I'm not sure what this query does exactly, but the image from linuxserver (https://hub.docker.com/r/linuxserver/rutorrent) didn't have to do that in order to handle ip changes and it works just fine with dynamic IP changes. Unfortunately this image has been deprecated and this is referenced and has of course some great features (geoIP). However the current handling of dynamic IP changes makes this image unusable at the moment.

**Comment by crazy-max** [comment]
@Ylawy In linuxserver image, the wan IP was not handled for the [rtorrent command](https://github.com/linuxserver/docker-rutorrent/blob/78113ffc2069d63fb4e1e012d4c4d4dba665f05c/root/etc/services.d/rutorrent/run#L11-L12) but here we [took it into account](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/aeba27c1c73d85c8af8852b6603d9a40395c9ad6/rootfs/etc/cont-init.d/04-create-services.sh#L28). That must be your issue. Maybe we could opt-out that behavior.

**Comment by SeeTwoArrr** [comment]
On the home page under environment variables it says it resolves your public IP using dig: `dig +short myip.opendns.com @resolver1.opendns.com`

I personally just use a VPN (specific server, with a specific IP) and deploy a gluetun container (2 in fact) as sidecar next to the rutorrent/rtorrent one.

**Comment by Ylawy** [comment]
@crazy-max I believe the fact that they didn't handle it was in this case actually a good thing. With setting the wan IP once at startup you will always encounter this problem when an IP changes.

**Comment by V33m** [comment]
Can I simply set `WAN_IP=0` (or 0.0.0.0) to disable the feature? For the time being, I don't truse to use the docker image since for whatever reason, my actual IP is found. Even though the container is connected through a vpn in a docker-compose file with:
```
    depends_on:
      - openvpn
    network_mode: "service:openvpn"
```

I've no idea how this is even possible, but it's enough for me to stay away unit this issue is addressed.
