### ISSUE TITLE
Run Script on Startup?

### ISSUE THREAD

**Issue by neo-neo1** [crazy-max/docker-rtorrent-rutorrent#132]
I use your container and need to run a simple .sh script on startup. Does it support launching scripts on startup? 

On all [LinuxServer.io containers you're able to achieve this](https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers) by placing a script `/config/custom-cont-init.d/onstart.sh` and mounting it appropriately.

Can someone with the ability please add a similar method to this project? It'll be greatly appreciated.

**Comment by SeeTwoArrr** [comment]
The image has a script for geoip in /etc/periodic/monthly. This called from root's crontab in `/etc/crontabs/root`. I think this means we have cron available to us, so you could make use of that.

Although, if you run rtorrent in kubernetes or a variation thereof, an init container doing the job is probably a better idea.

**Comment by crazy-max** [comment]
Custom scripting will not be added to this image. Feel free to fork or build on top of this image if you want.

**Comment by TMD20** [comment]
You can do basically the same thing just add the script to
/etc/cont-init.d/

Depending on where you want to do, you have to be careful about where you name the script
