### ISSUE TITLE
Webdav Directory

### ISSUE THREAD

**Issue by neo-neo1** [crazy-max/docker-rtorrent-rutorrent#133]
I've manually changed my download directory in rtorrent.rc However [webdav.conf is hardcoded to /downloads/complete](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/rootfs/tpls/etc/nginx/conf.d/webdav.conf). Is there no way to edit webdav.conf or dynamically insert download directory with an environmental variable?

**Comment by crazy-max** [comment]
https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/105#issuecomment-1112681278
