### ISSUE TITLE
Include Autodl-Irssi

### ISSUE THREAD

**Issue by borok34** [crazy-max/docker-rtorrent-rutorrent#136]
Hi, 
it would we really nice to see autodl-irssi added to this nice image!

Cheers

**Comment by Anon0511** [comment]
He already said that he isn't going to include it for "slim-ity" reasons.

Although, I have here 2 suggestions:
- Create a second version of this container, including autodl-irssi (honestly this is one of the main reasons why people still use rtorrent + rutorrent anyway)
- Providing a Guide how to get autodl-irssi in a standalone container and setting up the connection

Personally I was waiting for months now for either to happen, but now I want to push things. I just got a working container but can't seem to establish a connection.

**Comment by crazy-max** [comment]
* #79
* #13
