### ISSUE TITLE
Please add this

### ISSUE THREAD

**Issue by lordvalium** [crazy-max/docker-rtorrent-rutorrent#14]
Hi, first of all: Great docker container. Better than every other i tried. 

Could you please add this one? https://github.com/nelu/rutorrent-filemanager

Thank you. 
Cheers

**Comment by crazy-max** [comment]
Hi @lordvalium,

> Could you please add this one? https://github.com/nelu/rutorrent-filemanager

You can already custom plugins within this image. See [this section](https://github.com/crazy-max/docker-rtorrent-rutorrent#override-or-add-a-rutorrent-plugintheme) in the README for more info.

> Great docker container. Better than every other i tried.

Thanks for your support, glad you like it.
