### ISSUE TITLE
How to set maximum number of simultaneous downloads?

### ISSUE THREAD

**Issue by Nabukodonosor** [crazy-max/docker-rtorrent-rutorrent#144]
The title says it all. I've tried this in my rtorrent.rc file:

throttle.max_downloads.global.set = 1

As you can see, it still downloads all of them at the same time:
http://prntscr.com/26ncy33

I would like to set it to maximum 1 download at a time, and the rest of the to wait in queue. Last night I started 6 downoads an wanted to watch the first movie, but only later I found out that all 6 were downloading at the same time, so I had to wait for all 6 do be downloaded.

How can I accomplish this?

**Comment by lps-rocks** [comment]
` throttle.max_downloads.global.set ` doesn't work like that. `throttle.max_downloads.global` is the number of maximum simultaneous download slots. A "slot" is occupied not by a torrent in the downloading status but by a peer that rtorrent is downloading from. You'd need something like pyrotorque (a component of pyroscope) to automatically manage a queue of downloads.

**Comment by crazy-max** [comment]
closing as it's not directly linked to this image: https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md#closure-policy
