### ISSUE TITLE
OPCACHE_MEM_SIZE is missing unit of measurement in the README

### ISSUE THREAD

**Issue by newadventure079** [crazy-max/docker-rtorrent-rutorrent#158]
The README says `OPCACHE_MEM_SIZE: PHP OpCache memory consumption (default 128)`.  128, what?  bytes?  megabytes?

Also, other memory related attributes have `M` attached to them, ie. `MEMORY_LIMIT: PHP memory limit (default 256M)`, so should the value for OPCACHE_MEM_SIZE be `128` or `128M`?

**Comment by crazy-max** [comment]
`128` in megabytes: https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.memory-consumption
