### ISSUE TITLE
How can i see the rtorrent process on cli

### ISSUE THREAD

**Issue by lordvalium** [crazy-max/docker-rtorrent-rutorrent#16]
I've entered the running container via
`sudo docker exec -it name /bin/sh  `        (ash bash is not there..)

It seems that rtorrent is not running via screen or tmux. 
How can i see rtorrent CLI view? 

Thx

**Comment by crazy-max** [comment]
You can't. See https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/README.md#xmlrpc-through-nginx

**Comment by lordvalium** [comment]
Absolutely no way? Dont know the motivation or usage behind xmlrpc-through-nginx

**Comment by crazy-max** [comment]
No way. rTorrent is launched as a daemon. Only accessible through api (xmlrpc)
