### ISSUE TITLE
[Feature request] OpenVPN

### ISSUE THREAD

**Issue by enoch85** [crazy-max/docker-rtorrent-rutorrent#17]
Stumbled across this reading another issue on Github. The combination in this Docker image is awesome! Alpine <3.

Anyway, would be very nice if you would consider adding OpenVPN as an extra layer of protection. Maybe you can get some inspiration from here: https://github.com/binhex/arch-rtorrentvpn

**Comment by crazy-max** [comment]
@enoch85

> Anyway, would be very nice if you would consider adding OpenVPN as an extra layer of protection.

Better to keep this image as light as possible. What you can do is routing your container traffic through a VPN connection of a dedicated container.
Maybe this post can help you: https://jordanelver.co.uk/blog/2019/06/03/routing-docker-traffic-through-a-vpn-connection/

> Stumbled across this reading another issue on Github. The combination in this Docker image is awesome! Alpine <3.

Thanks!
