### ISSUE TITLE
plugin does not exist

### ISSUE THREAD

**Issue by newadventure079** [crazy-max/docker-rtorrent-rutorrent#177]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I'm seeing the following in the logs. I dont have any plugins disabled per the docker env vars

```
Setting custom config for create plugin...
  WARNING: create plugin does not exist

Setting GeoIP2 databases for geoip2 plugin...
  WARNING: geoip2 plugin does not exist
```

### Expected behaviour

All plugins should work

### Actual behaviour

create and geoip2 dont work per the log files.

I've also noticed the edit plugin isn't available and doesn't show up under the Plugins tab

### Steps to reproduce

Start container with no plugins disabled
View the logs

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 10
  Running: 10
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 20.10.3
 Storage Driver: btrfs
  Build Version: Btrfs v4.0
  Library Version: 101
 Logging Driver: db
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs db fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3fa00912415f3e9c6f82dd72119179d599efd13b
 runc version: 31cc25f16f5eba4d0f53e35374532873744f4b31
 init version: ed96d00 (expected: de40ad0)
 Security Options:
  apparmor
 Kernel Version: 4.4.180+
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.32GiB
 Name: DiskStation
 ID: TKJ6:OOPS:DLHP:LVJL:CDWA:JLVD:6O3A:OMQI:BHGE:VN4V:B7LE:JBLE
 Docker Root Dir: /volume3/@docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory TCP limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Version

docker-compose version 1.28.5, build 24fb474e
Linux DiskStation 4.4.180+ #42661 SMP Fri Apr 1 15:31:10 CST 2022 x86_64 GNU/Linux synology_v1000_1821+

### Docker compose

```yaml
n/a
```

### Container logs

Setting custom config for create plugin...
  WARNING: create plugin does not exist

Setting GeoIP2 databases for geoip2 plugin...
  WARNING: geoip2 plugin does not exist

**Comment by crazy-max** [comment]
Can't tell without seeing your compose file and full logs. Please create a proper [bug report](https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/new?assignees=&labels=&template=bug.yml).
