### ISSUE TITLE
Moving to rutorrent v4.0 in a develop tag?

### ISSUE THREAD

**Issue by the-lazy-fox** [crazy-max/docker-rtorrent-rutorrent#178]
Hi @crazy-max 
Would it be possible to get a docker tag (nightly / dev) which use the latest versions of rutorrent?
https://github.com/Novik/ruTorrent/releases/tag/v4.0-beta.1 

They have released interesting changes including some to make plugins like File Manager back on track.
https://github.com/nelu/rutorrent-filemanager/issues/33

Thank you for your help and answer!

**Comment by crazy-max** [comment]
I will not publish nightly releases but I will take a look to add support for v4.0 on another branch.

**Comment by stickz** [comment]
@crazy-max We are pleased to announce ruTorrent version 4.0 is now stable. We highly recommend using it over 3.10. There is significant enhancements. The web client is also more polished. https://github.com/Novik/ruTorrent/releases/tag/v4.0-stable

**Comment by mmccoy** [comment]
FWIW, I rebuilt the image with the latest commit from rutorrent ([06222a00375bdd0f1f1b5b58bda29e7025316428](https://github.com/Novik/ruTorrent/commit/06222a00375bdd0f1f1b5b58bda29e7025316428)) and geoip ([f63f84c18f00c19622b83e96ae9dd8632e318183](https://github.com/Micdu70/geoip2-rutorrent/commit/f63f84c18f00c19622b83e96ae9dd8632e318183)), and it "just works" -- stoked to see all these perf improvements!

**Comment by crazy-max** [comment]
Can be tested with:

```
crazymax/rtorrent-rutorrent:edge@sha256:d3f3e4d3dfdc6340e083047fdaf82ea53ad34df4e60c77106e7420bd7b176ad7
```
