### ISSUE TITLE
Would it be possible to add --restart always to the docker compose script?

### ISSUE THREAD

**Issue by jahruhn** [crazy-max/docker-rtorrent-rutorrent#179]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

### Description

Would it be possible to add --restart always to the docker compose script?
So Rutorrent does restart when I the host is rebooted.

### Expected behaviour

The service is running when the host is rebooted

### Actual behaviour

it does not start automatically

### Steps to reproduce

Please add: "  --restart always to the docker compose script after the run command

### Docker info

```yaml
..
```

### Version

* Docker compose version (type `docker-compose --version`):
* System info (type `uname -a`):
 Latest

RPI 3B with Ubuntu Core 22

### Docker compose

```yaml
..
```

### Container logs

..

### Additional info

..

**Comment by crazy-max** [comment]
Already there: https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/7eec97f0a71826f802ddb697706d6abf62815ce4/examples/compose/docker-compose.yml#L45
