### ISSUE TITLE
"Remove torrent" deletes data

### ISSUE THREAD

**Issue by rj452** [crazy-max/docker-rtorrent-rutorrent#18]
Everytime I remove a torrent from the Rutorrent it deletes the downloaded data as well.

**Comment by crazy-max** [comment]
@rj452 Just comment [this section](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/2493d7ad8fd79d35ab40d2d4472b6310f636edb2/rootfs/tpls/.rtorrent.rc#L65-L66) in your .rtorrent.rc
