### ISSUE TITLE
getplugins.php taking 5 seconds to load

### ISSUE THREAD

**Issue by BloodyIron** [crazy-max/docker-rtorrent-rutorrent#182]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I've spun up the latest image from dockerhub, and I have a completely blank install. I don't have any torrents active, and have only really changed the theme as for the config.

I have /downloads and /data mounted to SMB shares, which works plenty fast with my existing non-docker (but old as nails) rtorrent/rutorrent set up, so I don't think that's related to the slowness I'm seeing.

But the matter is every time I load the page, or even refresh, "getplugins.php" takes 5 full seconds to load. Every. Single. Time.

Also, I'm loading this with a YAML manifest in k8s, so I'm not doing a stand-alone docker, this is IaC.

These are the Environment Variables I've declared in the YAML:

```
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "REDACTED"
        - name: RT_DHT_PORT
          value: "50000"
        - name: RT_INC_PORT
          value: "50000"
        - name: RU_REMOVE_CORE_PLUGINS
          value: "diskspace,extsearch,feeds,filedrop,geopip2,httprpc,ipad,rss,rssurlrewrite,unpack"
        - name: OPCACHE_MEM_SIZE
          value: "512"
        - name: RU_PHP_USE_GZIP
          value: "true"
        - name: RU_RPC_TIME_OUT
          value: "1"
```

### Expected behaviour

More like 50-300ms, not 5000ms load time

### Actual behaviour

I've already explained this in the Description

### Steps to reproduce

I've already explained this in the Description

### Docker info

```yaml
RKE k8s set up, in cluster configuration.
```

### Version

NA

### Docker compose

```yaml
NA
```

### Container logs

The container logs only show nginx output, combinations of HTTP304/200, which don't seem concerning at all. Initialisation logs show everything is working fine, no errors reported.

### Additional info

Could not find a solution on the internet that seemed to make it faster at all :(

**Comment by BloodyIron** [comment]
Seriously, why is this so slow? This makes the initial page load take FOREVER! And I can't find a way to speed this up >: |

**Comment by crazy-max** [comment]
Not an issue with the image itself but ruTorrent. Open an issue on upstream repo at https://github.com/Novik/ruTorrent

See also:
* https://github.com/Novik/ruTorrent/issues/1808
* https://github.com/Novik/ruTorrent/issues/1986
* https://github.com/Novik/ruTorrent/issues/1878

**Comment by BloodyIron** [comment]
Thanks @crazy-max !

**Comment by stickz** [comment]
Hi @crazy-max, I'm one of the collaborators on ruTorrent. We do not recommend using the master branch because there could be regressions. It's better to use the latest `pre-release` instead. We are proactive at versioning now to increase stability.

That being said, I believe this to be a separate issue. The experiential JavaScript Sanitation class we just added will not cause this type of problem to happen. But it could potentially cause other issues because it hasn't been thoroughly tested yet.

This issue is probably related to the user hardware or software configuration - not the ruTorrent web client. I was wondering if you'd like steps to add `vmtouch` to your software package. Resource usage is tiny. It greatly improves speed & stability. If disk resources are desperate, it could cause the ruTorrent web client to become unstable. It's still too heavily i/o bound right now.

**Comment by BloodyIron** [comment]
@stickz the interconnects between my k8s cluster and my storage are multiple 1gige LACP bonds, and the storage backing the application aspect of the VM (namely, not the actual torrent data, but the container and config itself) is backed by striped-mirrored SSD (4x SSDs in total) with ZFS. So this performance characteristic in no way should be storage limited.

I do appreciate you chiming into this! And I'm open to more ideas on what can be done about this :) It's really frustrating :(

**Comment by stickz** [comment]
@BloodyIron Please try the latest master version. I fixed a critical performance issue with `xmlrpc-c` in #198.

**Comment by BloodyIron** [comment]
@stickz yes sir! I'll try that promptly :)

**Comment by BloodyIron** [comment]
@stickz getplugins.php still taking 5-6 seconds to load, each time :( tried refreshing multiple times, same result.

**Comment by stickz** [comment]
@BloodyIron #202 is submitted to address performance issues with the build environment. We are lacking optimizations here.

**Comment by BloodyIron** [comment]
@stickz man I am seriously appreciating your support here! Thanks! I'm excited :DDD Thanks for your work on this and other things! \o/

**Comment by stickz** [comment]
@BloodyIron the ruTorrent version is 2 years outdated. It's still running 3.10 (which we don't support anymore). You will have to wait until we release version 4.0 stable before the author upgrades. Ping me again in a couple weeks, if it's not done yet.
