### ISSUE TITLE
Re-downloading old or already loaded episodes

### ISSUE THREAD

**Issue by damirabal** [crazy-max/docker-rtorrent-rutorrent#186]
Since a few weeks, my system has been re-downloading already loaded or previously downloaded eiposodes. The funny thing is that it downloads files which no longer exist on the RSS feed anymore.

For example, the series House of Dragon, the feed lists episode S01E09 (new), it downloads it fine but also downloads S01E02 which was downloaded a few weeks back and is no longer in the live RSS feed.

It is happening with multiple TV shows.

**Comment by damirabal** [comment]
Nothing?

Noone?

**Comment by damirabal** [comment]
Look at this screenshot. You'll see that the RSS feed has only one item that matches the filter but the filter match test shows two findings.

![ShowRSS Feed Handmaids Tale](https://user-images.githubusercontent.com/8690142/198101343-43c796e8-ddc7-4e84-9e93-b0f30663d440.png)

**Comment by crazy-max** [comment]
This repo don't bring support for ruTorrent or rtorrent as stated in https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md#closure-policy. Open an issue on upstream repo: https://github.com/Novik/ruTorrent

See also:
* https://github.com/Novik/ruTorrent/issues/1630
