### ISSUE TITLE
bad_alloc on rocky 9

### ISSUE THREAD

**Issue by vincentDcmps** [crazy-max/docker-rtorrent-rutorrent#188]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

when I launch container on a rocky linux 9 VM rtorrent pop this log 
```rtorrent: std::bad_alloc```
and rutorrent can't  connect to rtorrent so I suppose that he is freezing
I have try to launch same container on arch VM and Rocky 8 VM no issue meet

### Expected behaviour

run ccontainer correctly without issue

### Actual behaviour

cant use rutorrent

### Steps to reproduce

- on a rocky linux 9
- launch ``` docker run  crazymax/rtorrent-rutorrent```

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
ERROR: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": dial unix /var/run/docker.sock: connect: permission denied
errors pretty printing info
```

### Version

* Docker compose version (type `docker-compose --version`):
* System info (type `uname -a`):

### Docker compose

```yaml
uname:
linux corwin 5.14.0-70.30.1.el9_0.x86_64 #1 SMP PREEMPT Thu Nov 3 20:29:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Container logs

```
ervices.d] starting services
2022/11/11 16:22:16 [notice] 514#514: using the "epoll" event method
2022/11/11 16:22:16 [notice] 514#514: nginx/1.21.1
2022/11/11 16:22:16 [notice] 514#514: built by gcc 10.3.1 20211027 (Alpine 10.3.1_git20211027)
2022/11/11 16:22:16 [notice] 514#514: OS: Linux 5.14.0-70.30.1.el9_0.x86_64
2022/11/11 16:22:16 [notice] 514#514: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
2022/11/11 16:22:16 [notice] 514#514: start worker processes
2022/11/11 16:22:16 [notice] 514#514: start worker process 530
2022/11/11 16:22:16 [notice] 514#514: start worker process 531
rtorrent: std::bad_alloc
[11-Nov-2022 16:22:16] NOTICE: fpm is running, pid 512
[services.d] done.
[11-Nov-2022 16:22:16] NOTICE: ready to handle connections
rtorrent: std::bad_alloc
rtorrent: std::bad_alloc
rtorrent: std::bad_alloc
rtorrent: std::bad_alloc
rtorrent: std::bad_alloc
rtorrent: std::bad_alloc
rtorrent: std::bad_alloc
rtorrent: std::bad_alloc
rtorrent: std::bad_alloc
rtorrent: std::bad_alloc
rtorrent: std::bad_alloc
rtorrent: std::bad_alloc
```

**Comment by vincentDcmps** [comment]
if Iaunch container with podman no issue meet

**Comment by thirstyraven** [comment]
I'm facing the exact same issue on Fedora 37 as well.

```bash
$ uname -r
6.0.15-300.fc37.x86_64
$ docker --version
Docker version 20.10.22, build 3a2c30b
```

**Comment by bachmma1** [comment]
I face the same issue on photon OS 5
```
$ uname -a 
Linux <REDACTED> 6.1.90-1.ph5-esx #1-photon SMP Sat May 18 08:01:52 UTC 2024 x86_64 GNU/Linux

$ docker --version
Docker version 24.0.5, build ced0996
```
And solved it based on this [SO-Article](https://stackoverflow.com/questions/75536471/rtorrent-docker-container-failing-to-start-saying-stdbad-alloc) resp. the linked [DockerForum](https://forums.docker.com/t/weird-sc-open-max-value/135297/6)

```
docker run --ulimit nofile=32768:32768 crazymax/rtorrent-rutorrent:latest
```
The `ulimit nofile` parameter did the trick. I interpreted the documentation as it is the amount of RAM in MB to set. 
So in my case 32 GB of RAM on VM -> forward 32 GB of RAM to the docker container.

Without the `ulimit nofile` the command `ulimit -n` showed 1073741816 inside the container. I guess this is too much.

Hope this helps ;)

**Comment by vincentDcmps** [comment]
@bachmma1  seem works thanks
