### ISSUE TITLE
Add a webroot environment variable

### ISSUE THREAD

**Issue by gauth-fr** [crazy-max/docker-rtorrent-rutorrent#19]
First thank you for your great image. The only one up-to-date allowing rtorrent.rc scripting, i.e moving torrent without problem. Maybe due to compliling everything rather than using the rtorrent from apk.. well, thank you :)

Would it be possible to add an environment variable (and the according process) to set rutorrent web root, so i can be reached thru something like http://xxxx/mywebroot

Why? 
Because with traefik, i'd rather use URLs than subdomain.
And even if i achevied, with traefik config, routing the request correctly to the container using a custom webroot , rutorrent won't consider this "webroot", so all the following needed resources requested by rutorrent  (JS, CSS & so on) won't load (since they won't contain the webroot).
I don't really know if 'im clear...

**Comment by crazy-max** [comment]
Hi @gauth-fr,

This is not possible for ruTorrent. Base path is hardcoded.

But you can override the [`index.html](https://github.com/Novik/ruTorrent/blob/master/index.html)` with a custom `base` element in the head section of the HTML file with something like `<base href="http://xxxx/mywebroot/">` and bind mount this file in the container with `-v "./index.html:/var/www/rutorrent/index.html"`.

**Comment by nightah** [comment]
> This is not possible for ruTorrent. Base path is hardcoded.

You can work around this within your reverse proxy with rewrites.
Below is an example of the required middleware to run this container under a subpath with Traefik:

```yaml
      - traefik.http.middlewares.add-trailingslash.redirectregex.regex=^(https?://[^/]+/[a-z0-9_]+)$$
      - traefik.http.middlewares.add-trailingslash.redirectregex.replacement=$${1}/
      - traefik.http.middlewares.add-trailingslash.redirectregex.permanent=true
      - traefik.http.middlewares.stripprefix.stripprefixregex.regex=/[a-z0-9_]+
      - traefik.http.middlewares.trailingslash.chain.middlewares=add-trailingslash,stripprefix
```

And the following is the actual label configuration for the rtorrent-rutorrent container specifically applying the `trailingslash` chain middleware:

```yaml
  rtorrent:
    image: crazymax/rtorrent-rutorrent
    container_name: rtorrent
    volumes:
      - /srv/docker/.rtorrent:/data
      - /mnt/nerv01:/downloads
    networks:
      - net
    expose:
      - 8080
    ports:
      - 50000:50000
    restart: unless-stopped
    environment:
      - RU_FORBID_USER_SETTINGS=true
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    labels:
      - traefik.enable=true
      - traefik.http.routers.rtorrent.rule=Host(`example.com`) && PathPrefix(`/rutorrent`)
      - traefik.http.routers.rtorrent.entrypoints=https
      - traefik.http.routers.rtorrent.middlewares=trailingslash
