### ISSUE TITLE
Remove torrent but keep data files

### ISSUE THREAD

**Issue by b0r0mir** [crazy-max/docker-rtorrent-rutorrent#190]
I think remove torrent should only remove the torrent from rtorrent but leave the data on the disk. remove and delete data should remove the data as well whereas remove should leave the data. However remove seems to delete the data files as well.
<img width="161" alt="Skærmbillede 2022-12-08 kl  12 43 53" src="https://user-images.githubusercontent.com/17888804/206438354-9a5ccf61-e06f-4a9c-a31b-23470ad264e7.png">
<img width="357" alt="Skærmbillede 2022-12-08 kl  12 41 14" src="https://user-images.githubusercontent.com/17888804/206437905-b4475689-e896-41df-b52d-f667e1820a05.png">

Both options seems to delete both torrent and data.

**Comment by crazy-max** [comment]
https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/129

**Comment by pwinnski** [comment]
The linked solutions absolutely does not work for me. I commented out the line, and then removed the line, and despite multiple restarts since, files disappear from the filesystem when the torrent is removed.
