### ISSUE TITLE
move config from /data to somewhere else

### ISSUE THREAD

**Issue by mountaser** [crazy-max/docker-rtorrent-rutorrent#192]
i have about 300 session files from another rtorrent installation and the mount point for the out directory was inside /data.
since /data is being used for the config and mounting the config inside of my data share (i use unraid) would make eveything messy. is there a way where i can move the config files from /data to something else like /config ?

**Comment by crazy-max** [comment]
We don't have migration path from other containers. You should start from scratch and copy over the session files to the new instance.
