### ISSUE TITLE
Improve traefik explanation

### ISSUE THREAD

**Issue by silentguy256** [crazy-max/docker-rtorrent-rutorrent#193]
Issue #110 asks what to do to enable https and the result ist just pointing to the traefik example folder. The explanation there is severely lacking though. it does not mention which values have to be set in the files. 
Not only is it not quite clear which values at which place have to be set for the letsencrypt request to go through (at LEAST all references to example.com have to be found and replaced) but in my first tests it still allowed access to the unencrypted rutorrent so it seems some ports have to be removed etc. This is not intuitive

Of cause "I don't want to explain all that" is a valid response, but it feels like then the example should be removed as it causes more confusion that is solves.

Same goes for the general example, it does not really say which values can/should be edited but at least without editing any of them it creates a usable environment. Although, it does not mention anywhere that it will keep throwing errors if you don't enter a geoip license key

**Comment by silentguy256** [comment]
Okay, I stand by my "there should be more intuitive documentation about what can/should be changed" but I have to take back my "just doing the obvious exposes unencrypted stuff" because after trying again it suddenly works. Guess I made a mistake in the obvious stuff that made traefik hiccup

**Comment by crazy-max** [comment]
These are just examples, if you want docs about how traefik works you sohuld take a look at https://doc.traefik.io/traefik/
