### ISSUE TITLE
Docker bind mounts are not sufficient workaround for rtorrent overriding RSS Manager plugin

### ISSUE THREAD

**Issue by pwinnski** [crazy-max/docker-rtorrent-rutorrent#194]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I have been using RSS Manager filters to save files into directories based on their filenames. I currently have 772 filters in rutorrent/share/settings/rss/cache/filters, each of which points to a different directory.

I have set custom bind mounts and permissions so that all of those directories are available to rT+ruT, and I can manually "Save to..." once the files are done, but because of the "hard-coded" /downloads/complete/ function, all 772 filters in RSS Manager are completely ignored.

I have read #44 and #105 and several related issues, but the final declaration (from #105) seems to be: 
"No need to change paths inside the container. The proper way to do this is to use custom [bind mounts](https://docs.docker.com/storage/bind-mounts/) on your side."

The insistence of this docker image to override the RSS Manager rules is not something that can be worked around with custom bind mounts. 

### Expected behaviour

RSS Manager rules, if set, should be respected, rather than *forcing* all downloads into predefined directories based on server. 

### Actual behaviour

All downloaded files are forced into /downloads/completed/Server/ no matter what plugin rules have set as the proper download location.

### Steps to reproduce

1. Set an RSS Manager filter with a value for "Directory"
2. Watch as the file is saved to /downloads/completed/Servername/ instead of the Directory you specified

### Docker info

```yaml
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 20.10.3
 Storage Driver: btrfs
  Build Version: Btrfs v4.0
  Library Version: 101
 Logging Driver: db
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs db fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3fa00912415f3e9c6f82dd72119179d599efd13b
 runc version: 31cc25f16f5eba4d0f53e35374532873744f4b31
 init version: ed96d00 (expected: de40ad0)
 Security Options:
  apparmor
 Kernel Version: 4.4.180+
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.32GiB
 Name: octonas
 ID: JMZ6:WII5:22VK:FVUL:BQ7Q:TMT2:QXZC:LWMD:4FZA:6F7D:5BVH:RXDH
 Docker Root Dir: /volume1/@docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory TCP limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Version

* Docker compose version (type `docker-compose --version`): docker-compose version 1.28.5, build 24fb474e
* System info (type `uname -a`): Linux octonas 4.4.180+ #42962 SMP Tue Oct 18 15:02:09 CST 2022 x86_64 GNU/Linux synology_v1000_1821+

### Docker compose

```yaml
N/A
```

### Container logs

N/A

**Comment by crazy-max** [comment]
> All downloaded files are forced into /downloads/completed/Server/ no matter what plugin rules have set as the proper download location.

Comment following lines in your `.rtorrent.rc` file: https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/1d7878a7fd1d5e0d69451bdacabd7dee63b81714/rootfs/tpls/.rtorrent.rc#L57-L60
