### ISSUE TITLE
moving torrents

### ISSUE THREAD

**Issue by euri10** [crazy-max/docker-rtorrent-rutorrent#2]
dunno if it's a config conflict between rtorrent amd rutorrent but when I save to another directory a completed torrent, it 1) redownloads it right away even with the Move data files and Fast resume checkbox set, and 2 ) reput it in the completed folder once done
Commenting those lines in .rtorrent.rc and restarting rtorrent solved the issue 2 but I couldn't figure out how to solve one.

```
method.insert = d.get_finished_dir, simple, "cat=$cfg.download_complete=,$d.custom1="
method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,$d.get_finished_dir="
```

**Comment by crazy-max** [comment]
As stipulated [here](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/assets/tpls/.rtorrent.rc#L60) and [here](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/assets/tpls/.rtorrent.rc#L65), you should not enable the same behavior on rTorrent and ruTorrent

**Comment by euri10** [comment]
so should I want to be able to move torrents once completed "manually" with rutorrent, removing those lines should suffice or do I need on top to set RU_REMOVE_CORE_PLUGINS to httprpc only you think ?
will test anyway,

**Comment by crazy-max** [comment]
For performance and security I think you should focus on rTorrent confgiuration. Anyway, what ruTorrent does is simply to send shell commands to rTorrent in RPC.
I have included [those lines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/assets/tpls/.rtorrent.rc#L60-L66) in the rTorrent config as an example but feel free to do like you want.

**Comment by euri10** [comment]
removing those lines effectively solves my "issue" and I can manually move a torrent from one folder to another once completed without a complete redownload,

I will certainly dig in the rtorrent documentation, I still dont get why with this config, the torrent once completed gets redownloaded as soon as Save To in rutorrent is made, as if it was tied to that completed directory.

thanks for the help
