### ISSUE TITLE
Separate download volume from config (data) volume

### ISSUE THREAD

**Issue by gauth-fr** [crazy-max/docker-rtorrent-rutorrent#20]
IMHO, it would better better to separate the downloads (with a new volume) from data volume (containing the configs)

Why... because, in my case, i want to mount this downloads volume in other containers (medusa,radarr or whatever).. 
For example... I would like `/files` in my, let's say, radaar instance which would contains
```
    /files/downloads (where rtorrent would store the downloads)
    /files/media (where radarr would store the renamed torrent & so on)
```
I need to mount in my radarr the common root /files because i want to use hardlink (i don't want symlink and even less file copy..), which is not possible between docker volumes.
And in rtorrent container, i would mount `/files/downloads` as let say `/downloads`...

To let you know, thru my compose file, i already did that:
```
volumes:
      - /home/grut/rtorrent/data:/data
      - /home/grut/rtorrent/passwd:/passwd
      - /home/grut/files/downloads:/downloads
```
But there are some side effects like webdav not pointing to this /downloads directory, need to overload the default in rtorrent.rc etc...

**Comment by crazy-max** [comment]
@gauth-fr Done.
