### ISSUE TITLE
Feature idea: OpenVPN

### ISSUE THREAD

**Issue by sorentorp** [crazy-max/docker-rtorrent-rutorrent#201]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Would it be possible to include OpenVPN in the image, so it is easier do do torrenting via a VPN-provider with OpenVPN configuration?

### Expected behaviour

Access via VPN :-)

### Actual behaviour

Cany find any hint of such feature.

### Steps to reproduce

1. It isn't there

### Docker info

```yaml
none.
```

### Version

lastest

### Docker compose

```yaml
.
```

### Container logs

.

**Comment by crazy-max** [comment]
https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/17#issuecomment-576048239
