### ISSUE TITLE
Upgrade to ruTorrent v4.0

### ISSUE THREAD

**Issue by djerfy** [crazy-max/docker-rtorrent-rutorrent#209]
Hi,

There is ruTorrent v4.0 out now, possible to update to this version?
No emergency, a lot of major changes...

https://github.com/Novik/ruTorrent/releases/tag/v4.0-stable

Thanks

**Comment by crazy-max** [comment]
This has been merged already: https://github.com/crazy-max/docker-rtorrent-rutorrent/pull/208

See also: https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/178#issuecomment-1374593285
