### ISSUE TITLE
How to hide some functions in 4.0?

### ISSUE THREAD

**Issue by renetsk** [crazy-max/docker-rtorrent-rutorrent#213]
Hello,
today I found there are new informations in new version of ruTorrent. Is there any way to hide informations like Open x http xx sock etc?

Thank you.

**Comment by crazy-max** [comment]
> like Open x http xx sock

Can you be more specific? If it's directly related to ruTorrent and not the image itself, I suggest to open an issue on the official repo instead: https://github.com/Novik/ruTorrent
