### ISSUE TITLE
Update for UnRaid

### ISSUE THREAD

**Issue by WarHawk8080** [crazy-max/docker-rtorrent-rutorrent#217]
I'm seeing unavailable update for this in UnRaid, is there an update?

**Comment by crazy-max** [comment]
Not sure what you mean but releases are there: https://github.com/crazy-max/docker-rtorrent-rutorrent/releases. For Docker tags see: https://hub.docker.com/r/crazymax/rtorrent-rutorrent/tags?page=1&ordering=last_updated
