### ISSUE TITLE
add more than 20 torrents at a time

### ISSUE THREAD

**Issue by deepika05** [crazy-max/docker-rtorrent-rutorrent#22]
Cannot add more than 20 torrents at a time as the "max_file_uploads = 20" is set in php. Could we please get a facility to edit this variable? thanks!

**Comment by deepika05** [comment]
or would it be better to have a php.ini additional config file somewhere on the mapped drive location to add custom parameters? i see multiple php parameters being passed along as env variables now. the linuxserver container has this implementation

**Comment by crazy-max** [comment]
@deepika05 You can try to mount PHP ini configs like `my.ini:/etc/php7/conf.d/thismy.ini`.

**Comment by deepika05** [comment]
thanks. i just did this and it seems to have fixed the max 20 torrents limitation! "/etc/php7/conf.d/php-local.ini". i increased the limit to 100 on my system.
