### ISSUE TITLE
Adding a /johndoe subpath in rutorrent listening URL (ex: https://rutorrent.mondomaine.fr/johndoe)

### ISSUE THREAD

**Issue by bazirico** [crazy-max/docker-rtorrent-rutorrent#223]
I'm trying to change the URL my rutorrent answers to. I'm using traefik as a reverse proxy. What I think : 

- User `johndoe` goes to `https://rutorrent.mondomaine.fr/johndoe` -> :white_check_mark: 
- Traefik grabs the request, strips `/johndoe` from the URL, and forwards the request to the right backend (a crazy-max/rtorrent-rutorrent image) -> :white_check_mark: 
- The nginx backend gets a request from the "normal" URL `https://rutorrent.mondomaine.fr/` -> :white_check_mark:
- rutorrent is able to tell my browser "hey, my resources are located here : `https://rutorrent.mondomaine.fr/johndoe`" -> :x:

### What I've done : 

I've modified and mount `/var/www/rutorrent/index.html` like this : 

```
<html>
...
<head>
  <base href="https://rutorrent.mondomaine.fr/johndoe/">
...
</head>
</html>
```

When I bash into my running container I've checked that my `index.html` is correctly mounted and contains my modification ->  :white_check_mark:

### My problem 

I've restarted my containers, but no luck so far. My browser is still trying to load rutorrent resources on `https://rutorrent.mondomaine.fr`, and not on `https://rutorrent.mondomaine.fr/johndoe`

- Is [this solution](https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/19#issuecomment-619921495) still valid ?
- Or maybe I'm not having the correct approach here, is there a workaround with the builtin nginx to do so ?

**Comment by nightah** [comment]
> This is not possible for ruTorrent. Base path is hardcoded.

You can work around this within your reverse proxy with rewrites.
Below is an example of the required middleware to run this container under a subpath with Traefik:

```yaml
      - traefik.http.middlewares.add-trailingslash.redirectregex.regex=^(https?://[^/]+/[a-z0-9_]+)$$
      - traefik.http.middlewares.add-trailingslash.redirectregex.replacement=$${1}/
      - traefik.http.middlewares.add-trailingslash.redirectregex.permanent=true
      - traefik.http.middlewares.stripprefix.stripprefixregex.regex=/[a-z0-9_]+
      - traefik.http.middlewares.trailingslash.chain.middlewares=add-trailingslash,stripprefix
```

And the following is the actual label configuration for the rtorrent-rutorrent container specifically applying the `trailingslash` chain middleware:

```yaml
  rtorrent:
    image: crazymax/rtorrent-rutorrent
    container_name: rtorrent
    volumes:
      - /srv/docker/.rtorrent:/data
      - /mnt/nerv01:/downloads
    networks:
      - net
    expose:
      - 8080
    ports:
      - 50000:50000
    restart: unless-stopped
    environment:
      - RU_FORBID_USER_SETTINGS=true
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    labels:
      - traefik.enable=true
      - traefik.http.routers.rtorrent.rule=Host(`example.com`) && PathPrefix(`/rutorrent`)
      - traefik.http.routers.rtorrent.entrypoints=https
      - traefik.http.routers.rtorrent.middlewares=trailingslash

**Comment by bazirico** [comment]
Big thanks @nightah 🚀 !

Your solution works perfectly, and without having to modify anything on the backend side. It's much more elegant. 🎩
