### ISSUE TITLE
set up mobile access (Transdrone)

### ISSUE THREAD

**Issue by Ylawy** [crazy-max/docker-rtorrent-rutorrent#228]
Hi,

How do I set up mobile access to the docker instance for example using Transdrone? With any other rtorrent instance the SCGI mount point is /RPC2 but this doesn't seem to work here. Has anybody been able to set this up successfully?

here are my settings in Transdrone:
IP: host IP
port: XMLRPC_PORT (default: 8000)
SCGI: /RPC2 (also tried: "/plugins/rpc/rpc.php")

Thank you!

**Comment by XxAcielxX** [comment]
Here are the working settings:

Server Type: rTorrent
IP or host name: <ip-here>
Port number: 8000
SCGI mount point: leave this empty

**Comment by ToNIX-** [comment]
I can't get this to work on Transdroid. All my ports are default (6881, 8000, 9000 and 50000), except for the web interface being 8040 instead of 8080. Do you have any idea?

**Comment by ToNIX-** [comment]
> Here are the working settings:
> 
> Server Type: rTorrent IP or host name: ip-here Port number: 8000 SCGI mount point: leave this empty

I can't get this to work on Transdroid. All my ports are default (6881, 8000, 9000 and 50000), except for the web interface being 8040 instead of 8080. Do you have any idea?
