### ISSUE TITLE
connect through mod.scgi

### ISSUE THREAD

**Issue by deepika05** [crazy-max/docker-rtorrent-rutorrent#23]
Not a bug or issue really. Could you please show how to connect to rtorrent through mod.scgi instead of RPC thereby i can remove both httprpc and rpc plugins? can rutorrent do this? i mean connect to the socket directly or through port 8000. also why is port 80 exposed? could not find it in your readme. thanks for an awesome container. very lean and mean!

**Comment by crazy-max** [comment]
Hi @deepika05,

> Could you please show how to connect to rtorrent through mod.scgi instead of RPC thereby i can remove both httprpc and rpc plugins?

Do you talk about Apache 2 mod scgi? If so this is not possible with this image. More info: https://github.com/crazy-max/docker-rtorrent-rutorrent#xmlrpc-through-nginx

> ...or through port 8000.

You can send XMLRPC request through [port 8000](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/1d14822e6a41b922b595b2a09ed624881615381c/rootfs/tpls/etc/nginx/conf.d/rpc.conf#L1-L14).

> ...also why is port 80 exposed?

If you talk about [this port](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/ca21644063200c4d1c6027f8e462b1baaf6478f3/examples/traefik/docker-compose.yml#L23-L24), this is only for Traefik (reverse proxy for [rutorrent](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/ca21644063200c4d1c6027f8e462b1baaf6478f3/examples/traefik/docker-compose.yml#L60-L63) and [webdav](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/ca21644063200c4d1c6027f8e462b1baaf6478f3/examples/traefik/docker-compose.yml#L63))

> thanks for an awesome container. very lean and mean!

Thanks!

**Comment by deepika05** [comment]
thanks! i think i understand now. so there isn't a way to remove RPC plugins then. thanks again!
