### ISSUE TITLE
Plugin HTTPRC not working

### ISSUE THREAD

**Issue by Majaxx** [crazy-max/docker-rtorrent-rutorrent#234]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

plugin not working plugins/httprpc/action.php
error 404

### Expected behaviour

 La résolution du problème 

### Actual behaviour

 Empeche le bon fonctionnement des applications tierces

### Steps to reproduce

 *

### Docker info

```yaml
*
```

### Version

* Docker compose version (type `docker-compose --version`):
* System info (type `uname -a`):
 Lastest

### Docker compose

```yaml
Lastest
```

### Container logs

 *

**Comment by crazy-max** [comment]
`RU_REMOVE_CORE_PLUGINS` defaults to `httprpc`, see https://github.com/crazy-max/docker-rtorrent-rutorrent#rutorrent. See `RU_REMOVE_CORE_PLUGINS=false` to avoid the plugin to be removed.
