### ISSUE TITLE
Heads up: Latest version has a bug with RSS Feeds

### ISSUE THREAD

**Issue by GH0STDATA** [crazy-max/docker-rtorrent-rutorrent#236]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I'm just giving the maintainers and everyone who uses this docker image a heads up that the latest version of ruTorrent that was released, v4.1.3, has a critical bug with RSS feeds where you cannot add a new RSS feed and they do not update on a set interval as they normally should. Reverting to 4.0.4 fixes the issue.

https://github.com/Novik/ruTorrent/pull/2498

A pull request is already in the works. This isn't really a bug report for the container itself, just a notification to let the everyone know about this current problem with the official ruTorrent repo.

### Expected behaviour

N/A

### Actual behaviour

N/A

### Steps to reproduce

N/A

### Docker info

```yaml
N/A
```

### Version

* Docker compose version (type `docker-compose --version`): N/A
* System info (type `uname -a`): N/A

### Docker compose

```yaml
N/A
```

### Container logs

N/A

**Comment by stickz** [comment]
Did you test the docker image? It already has `php-xml` installed and should work fine. This is not a critical bug. It's a fix for people who don't install the required project dependencies. @crazy-max this is invalid and can be closed.

**Comment by GH0STDATA** [comment]
Yes, I did. RSS feeds do not work for me at all on the latest docker image. I wouldn't have created this issue if it worked.

**Comment by GH0STDATA** [comment]
Here is the error I get in the Chrome dev console when I try to add an RSS feed:

![brave_JgCdWzMz7Y](https://user-images.githubusercontent.com/33645963/235329938-41172d40-ea80-4335-88bb-828d3850b8f9.png)
