### ISSUE TITLE
Infected by a cryptominer

### ISSUE THREAD

**Issue by derzyklus63** [crazy-max/docker-rtorrent-rutorrent#243]
This container silently comes with a cryptomining process acting backend.
It used 50% of my CPU in my syno...
Shame on you.

**Comment by crazy-max** [comment]
@derzyklus63 Any proof?

**Comment by stickz** [comment]
The lower end synology NAS models are dual core. This is normal, especially if it's an ARM CPU. rTorrent performs tracker scraping at startup, which can fully saturate a single thread. This behaviour is expected, from a software design standpoint.

User would have provided a screenshot of `htop` if they proof. This is definitely a false accusation with ignorance.
