### ISSUE TITLE
Use HTTPS via nginx proxy

### ISSUE THREAD

**Issue by chris30o0** [crazy-max/docker-rtorrent-rutorrent#250]
Hi,
I've been trying to figure out how to use this image behind an nginx proxy.
For HTTP, I'm using quite simply this line (among others) in nginx:
`http://172.20.0.2:7443/`
For rtorrent, I'm basically using the default config example with 7443 as RUTORRENT_PORT.
This works nicely and I can access the webUI via my custom domain.

Obviously, I'd like to add HTTPS to that but this seems to be more complicated. I see the solution using traefik but as I'm running nginx proxy anyways I'd prefer to use this instead of an additional container.
It is unclear to me, how the rtorrent container interacts with traefik.

What needs to be configured so rtorrent will listen to HTTPS on whatever port?

**Comment by boomboxnation** [comment]
This seems like an nginx question.  But look at letsencrypt, it basically does everything for you.

**Comment by chris30o0** [comment]
SSL in nginx isn't the problem. I have a second configuration that does just that (forward HTTPS to a docker container).
However, RUTORRENT_PORT seems to be HTTP only.
If I connect to that port using SSL I always get a SSL version mismatch

**Comment by boomboxnation** [comment]
The Bittorrent Protocol is not the Hyper Text Transport Protocol.  Your nginx should effectively be doing a straight-up port forward. Tho personally I would just tell the docker to open that port on the external interface.

**Comment by boomboxnation** [comment]
I misunderstood. Twice. Why not leave that internal communication in the clear? Most the reason for using the reverse proxy is to offload SSL.

**Comment by chris30o0** [comment]
I'm running other websites on that server so I can't have docker listen on 443. That's what I need the nginx proxy for.
I haven't figured out yet on which port the docker container is accepting HTTPS traffic at all. It does not appear to be the RUTORRENT_PORT. If that port should accept HTTPS then there is something wrong in my setup but I need someone to tell me how it's supposed to be.
This is the main issue

**Comment by chris30o0** [comment]
I'll keep it short and simple:
Does RUTORRENT_PORT accept SSL traffic?

**Comment by chris30o0** [comment]
Within the docker container there is literally an nginx container running.
IMHO, rutorrent not supporting https is a bug. We're in 2023 - nobody should use plain http anymore.

I realize now that by containerizing rtorrent I didn't really do myself a favor. I'll go back to running it on the machine directly with my own nginx.

**Comment by chris30o0** [comment]
In this case, 'Your cool service' equals the docker container so what you're suggesting is basically this:

![Unbenanntes Diagramm drawio](https://github.com/crazy-max/docker-rtorrent-rutorrent/assets/13258847/d50dda89-45d1-43b3-a99d-c03aab35d721)
