### ISSUE TITLE
Port Check Plugin

### ISSUE THREAD

**Issue by Hipoglos** [crazy-max/docker-rtorrent-rutorrent#253]
For some reason, the port checker pluging stopped working suddenly. Is anyone else having this issue? (Port Status Unknown). I don't remember doing any change on my config that could affect this.

**Comment by Ben-Atherton** [comment]
You're not the only one, I have the same issue.

<img width="116" alt="Screenshot 2023-07-26 at 12 40 28" src="https://github.com/crazy-max/docker-rtorrent-rutorrent/assets/18259912/c9e2c66b-a40e-4051-b63b-a2ba1a469219">
