### ISSUE TITLE
Errors on pnlViews section

### ISSUE THREAD

**Issue by codog180** [crazy-max/docker-rtorrent-rutorrent#287]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When creating a new pnlView there is no way to name the view. Additionally when right clicking on a view there is a JS Error TypeError:theUILang.MoveView is undefined.

### Expected behaviour

To be able to name the view as well as for right click functionality to work. 

### Actual behaviour

No option to rename the view just a default name is given. Unable to right click JS error happens every time. 

### Steps to reproduce

1. Open ruTorrent
2. create new view under pnlViews
3. Try to rename view or right click on new view

### Docker info

```text
Password:
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.23
 Storage Driver: btrfs
  Build Version: Btrfs v4.0
  Library Version: 101
 Logging Driver: db
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs db fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b23a389d8c181697302d163356e97dec04eb8d88
 runc version: 5af893d
 init version: ed96d00
 Security Options:
  apparmor
 Kernel Version: 4.4.302+
 Operating System: Synology NAS

 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.32GiB
 Name: Server
 ID: W4IZ:YKAL:ROAT:4VQZ:ZUUH:LUJP:34L3:ZGUK:I4UM:WG7O:LBYW:RKSA
 Docker Root Dir: /volume1/@docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No kernel memory TCP limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Logs

```text



### Additional info

_No response_

**Comment by stickz** [comment]
Please file an issue on the ruTorrent GitHub. This is not related to the docker container.
https://github.com/Novik/ruTorrent/issues
