### ISSUE TITLE
Implement the ability to use a dynamic 'incoming port' for rtorrent - to use with Gluetun

### ISSUE THREAD

**Issue by notDavid** [crazy-max/docker-rtorrent-rutorrent#314]
### Description

[Gluetun](https://github.com/qdm12/gluetun) has [added the ability](https://github.com/qdm12/gluetun/issues/1488) to use Port Forwarding for VPN providers, documented [here](https://github.com/qdm12/gluetun-wiki/blob/29e3dee5024d82218e3f170b32f027102ff84aab/setup/advanced/vpn-port-forwarding.md)

Would be really cool if we could set `RT_INC_PORT` dynamically, by using this functionality.
The (random) opened port number by the VPN provider can be obtained via the Control Server. For example: `curl 192.168.1.5:8000/v1/openvpn/portforwarded`

**Comment by stickz** [comment]
It's required to restart `rTorrent` anyways when changing the port. Is it possible to restart the docker container with that environment variable? There should be a graceful exit, assuming your configuration works properly.
