### ISSUE TITLE
Update to 4.3.0 not possible - rutorrent breaks

### ISSUE THREAD

**Issue by dstyp** [crazy-max/docker-rtorrent-rutorrent#345]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Wanted to update to 4.3.0 but it breaks. Had to revert and am now using     image: crazymax/rtorrent-rutorrent:4.2.9-0.9.8_2-0.13.8_2
 in compose.yml.

### Expected behaviour

Rutorrent to work

### Actual behaviour

Many error messages, I have a screen shot

[15.05.2024 21:59:06] WebUl started.
[15.05.2024 21:59:07]JS error: [http://192.168.1.100:8080/: 3015] Uncaught ReferenceError: injectCustomElementCSS is not defined
[15.05.2024 21:59:071 Bad response from server: (404 [error,listl) < html> <head> < title >404 Not Found</title></head> <body> ‹center> <h1>404 Not Found</h1></center> <hr> <center>nginx</center>
page -->  
<img width="1206" alt="Screenshot 2024-05-15 at 21 59 30" src="https://github.com/crazy-max/docker-rtorrent-rutorrent/assets/24799250/4a4d3ee3-d7e7-483f-8897-79ff5e75e1f5">

### Steps to reproduce

1 set compose.yml to latest
2 pull & start
3 doesnt work

### Docker info

```text
Client: Docker Engine - Community
 Version:    26.1.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 8
  Running: 6
  Paused: 0
  Stopped: 2
 Images: 99
 Server Version: 26.1.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-20-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.2GiB
 Name: dsrvxxii
 ID: 30913477-cafc-44ba-86d0-1eafd7a92d18
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Logs

```text
will have to get back on this
```

**Comment by SnorreSelmer** [comment]
Yep, having the exact same issue here. `latest` fails to work with a 404, `4.2.9-0.9.8_2-0.13.8_2` works fine

**Comment by stickz** [comment]
Hello @dstyp @SnorreSelmer There are two steps required to upgrade to latest.

1) Clear your web browser cache.
2) Set `RU_REMOVE_CORE_PLUGINS` environment variable to `false`. The 404 error is caused by removing the `httprpc` plugin from the previous version of the docker container. This is now required for `ruTorrent v4.3.0`, as we dropped support for `rpc`.

Please do not hesitate to ask, if you have any further questions about this version upgrade. There are very significant and impactful changes to the docker container. It highly recommended to invest 15 minutes of your time into upgrading.

**Comment by crazy-max** [comment]
> Set RU_REMOVE_CORE_PLUGINS environment variable to false. 

@stickz Let me know if we should add this to the changelog or feel to open a PR 👍

**Comment by stickz** [comment]
@dstyp @SnorreSelmer Please pull the latest ruTorrent v4.3.1 docker image @crazy-max just tagged. This will automatically resolve your problem. You'll receive a warning instead and ruTorrent v4.3.1 will load successfully.

**Comment by dstyp** [comment]
@stickz @crazy-max great stuff just in time for the weekend. Thank you for the efforts! 🙏⭐️
