### ISSUE TITLE
stickz rtorrent build unable to leech from qBittorrent, Deluge, Transmission clients

### ISSUE THREAD

**Issue by GH0STDATA** [crazy-max/docker-rtorrent-rutorrent#354]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

It seems that there is a bug with [stickz's rtorrent repo](https://github.com/crazy-max/docker-rtorrent-rutorrent/pull/347), I cannot leech from qBittorrent, Deluge, or Transmission clients, which are 3 of the most popular torrent clients, especially on public trackers. Clients like BiglyBT, libTorrent (Rakshasa) 0.13.8, and a few other uncommon clients seem to work fine though. 

This is impacting my download speeds tremendously. The official rtorrent repo does not have this issue, I've noticed that this started to happen once I updated to the latest release of this docker container, which switches over to the stickz repo of rtorrent. I've attached an image below, I'm connected to over 50 seeders, but I'm unable to leech from any of the qBittorrent or Transmission clients. I will be reverting to an older version of this docker container until this is resolved or it is switched back to the official rtorrent repo.

![image](https://github.com/crazy-max/docker-rtorrent-rutorrent/assets/33645963/d4b760d1-f6a2-4884-8c0f-39e454b831e1)

### Expected behaviour

I should be able to leech from any available seeders no matter which client is being used.

### Actual behaviour

I cannot leech from any seeders who are using qBittorrent, Deluge or Transmission. Only a select few torrent clients are leech-able with stickz rtorrent repo. 

### Steps to reproduce

1. Install docker container.
2. Download a torrent, preferably a well seeded one on a public tracker.
3. Look at the peers and see who you're leeching from. Any qBittorrent, Transmission, or Deluge clients cannot be leeched from.

### Docker info

```text
Version:    26.0.0
Context:    default
Debug Mode: false
Plugins:
 buildx: Docker Buildx (Docker Inc.)
   Version:  v0.13.1
   Path:     /usr/libexec/docker/cli-plugins/docker-buildx
 compose: Docker Compose (Docker Inc.)
   Version:  v2.25.0
   Path:     /usr/libexec/docker/cli-plugins/docker-compose
```

### Logs

The logs do not provide any insight into this issue, I'm not seeing any errors or anomalies at all. If you need specific logs outside of the logs of the container itself, please let me know.

**Comment by GH0STDATA** [comment]
I can confirm that downgrading to the [4.3.1-0.9.8_3-0.13.8_2-r0](https://github.com/crazy-max/docker-rtorrent-rutorrent/releases/tag/4.3.1-0.9.8_3-0.13.8_2-r0) release of this docker container alleviates this issue for now.

**Comment by stickz** [comment]
Problem resolved. It was just the block size on the download delegator. Simple 1 line fix.

**Comment by stickz** [comment]
@GH0STDATA Please feel free to grab the fix from docker edge, while you wait for a release to be tagged.

**Comment by GH0STDATA** [comment]
> Problem resolved. It was just the block size on the download delegator. Simple 1 line fix.

Thanks for the really quick fix! I can confirm that the edge build is working fine now.

**Comment by stickz** [comment]
> > Problem resolved. It was just the block size on the download delegator. Simple 1 line fix.
> 
> Thanks for the really quick fix! I can confirm that the edge build is working fine now.

No problem. Enjoy the performance and stability benefits of the new rTorrent version.

**Comment by GH0STDATA** [comment]
Will do, keep up the great work!
