### ISSUE TITLE
Add autodl-irssi

### ISSUE THREAD

**Issue by JuezFenix** [crazy-max/docker-rtorrent-rutorrent#391]
### Description

I think it would be very useful to add autodl-irssi:
https://github.com/autodl-community/autodl-irssi.git
And the plugin for rutorrent:
https://github.com/autodl-community/autodl-rutorrent

You could use the scripts at https://github.com/irssi/scripts.irssi.org to take references.

**Comment by crazy-max** [comment]
https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/136#issuecomment-1112669656

**Comment by BHWarrior** [comment]
There is a modern and far better tool than AutoDL-irssi called [Autobrr](https://github.com/autobrr/autobrr)
