### ISSUE TITLE
rtorrent .rtlocal.rc forcing temp and complete folder inside download directory

### ISSUE THREAD

**Issue by zmiguel** [crazy-max/docker-rtorrent-rutorrent#44]
These 3 lines force us to have a complete and temp folders inside our download dir.
https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/35be9d3609cae0f7f4481ff178c9ab51a135e99c/rootfs/tpls/etc/rtorrent/.rtlocal.rc#L7-L8

https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/35be9d3609cae0f7f4481ff178c9ab51a135e99c/rootfs/tpls/etc/rtorrent/.rtlocal.rc#L18

I've tried removing them but every time I restart the container they are back. If I delete the folders the container crashes.

I don't really want to have these 2 random folders in my download directory. 

What can I do to get right of them without having to custom build the container?

Thanks!

**Comment by crazy-max** [comment]
@zmiguel Just remove these lines in your `/data/rtorrent/.rtorrent.rc` config:

```
# Move finished (no need Autotools/Automove plugin on ruTorrent)
method.insert = d.get_finished_dir, simple, "cat=$cfg.download_complete=,$d.custom1="
method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,$d.get_finished_dir="
```

And add this one at the end:

```
directory.default.set = (cat,(cfg.download))
```
