### ISSUE TITLE
rtorrent: Failed to parse command line option: Could not set local address: Try again.

### ISSUE THREAD

**Issue by callumjo** [crazy-max/docker-rtorrent-rutorrent#45]
Im getting this error on the docker logs:

rtorrent: Failed to parse command line option: Could not set local address: Try again.

My rutorrent webui looks like this:
![image](https://user-images.githubusercontent.com/77127967/103953744-984bf580-513a-11eb-9b86-779f40621cba.png)

**Comment by callumjo** [comment]
Its now showing this

![Uploading image.png…]()

**Comment by sun1ight** [comment]
Same issue with IPv6 enabled host, fixed with ipv4 WAN_IP variable.

**Comment by callumjo** [comment]
Thats fixed it. Thanks

I get this showing on the bottom bar of rutorrent. If I hover over it it says "port 50000 is closed. Is this an issue? Seems to be working fine. 
![image](https://user-images.githubusercontent.com/77127967/104307658-6aaed580-54c7-11eb-9a72-c88be58a32b1.png)

**Comment by crazy-max** [comment]
Please create a proper [bug report](https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/new?assignees=&labels=&template=bug_report.md)
