### ISSUE TITLE
50000: port is closed

### ISSUE THREAD

**Issue by callumjo** [crazy-max/docker-rtorrent-rutorrent#46]
On rutorrent web UI, at the bottom I am seeing this:

#### Steps to reproduce this issue
![image](https://user-images.githubusercontent.com/77127967/104469268-43800300-55b0-11eb-86b9-5ec8b985ba25.png)
When I hover over it I see '50000: port is closed.

* Docker version (type `docker --version`) :
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:43 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

* Docker compose version if applicable (type `docker-compose --version`) : 
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 20.04 Focal Server

System info (type `uname -a`) : 
Linux Ubuntu-2004-Server 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

 Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

  rtorrent-rutorrent:
    image: crazymax/rtorrent-rutorrent:latest
    container_name: rtorrent-rutorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WAN_IP=<hidden>
    env_file:
      - rtorrent-rutorrent.env
    volumes:
      - /.config/rutorrent/config:/data
      - /local/Downloads:/downloads
      - /.config/passwd:/passwd
    ports:
      - 9000:9000
      - 6881:6881
      - 6262:8080
      - 50000:50000
      - 5000:5000
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: unless-stopped

rtorrent-rutorrent.env
MEMORY_LIMIT=256M
UPLOAD_MAX_SIZE=16M
OPCACHE_MEM_SIZE=128
MAX_FILE_UPLOADS=50
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=remote_addr

XMLRPC_AUTHBASIC_STRING=rTorrent XMLRPC restricted access
RUTORRENT_AUTHBASIC_STRING=ruTorrent restricted access
WEBDAV_AUTHBASIC_STRING=WebDAV restricted access

RT_LOG_LEVEL=info
RT_LOG_EXECUTE=false
RT_LOG_XMLRPC=false

RU_REMOVE_CORE_PLUGINS=erasedata,httprpc
RU_HTTP_USER_AGENT=Mozilla/5.0 (Windows NT 6.0; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0
RU_HTTP_TIME_OUT=30
RU_HTTP_USE_GZIP=true
RU_RPC_TIME_OUT=5
RU_LOG_RPC_CALLS=false
RU_LOG_RPC_FAULTS=true
RU_PHP_USE_GZIP=false
RU_PHP_GZIP_LEVEL=2
RU_SCHEDULE_RAND=10
RU_LOG_FILE=/data/rutorrent/rutorrent.log
RU_DO_DIAGNOSTIC=true
RU_SAVE_UPLOADED_TORRENTS=true
RU_OVERWRITE_UPLOADED_TORRENTS=false
RU_FORBID_USER_SETTINGS=false
RU_LOCALE=UTF8

Dont think this is a bug its something that im doing wrong

**Comment by callumjo** [comment]
Solved this by changing (in docker-compose.yml):

- 50000:50000
to
- '50000:50000'

**Comment by bepstein111** [comment]
There's no way that could have fixed anything, plus, I'm having the same issue on portainer, and I can't just add quotes into my configuration. There's gotta be an underlying issue here, I have 50000 opened up everywhere possible and no dice. I really don't understand what the issue is, running netstat within the docker container returns `tcp        0      0 :::50000                :::*                    LISTEN      -`

Is this an IPv4 vs IPv6 issue? Literally pulling hair out of my head trying to figure this out.

**Comment by FarisCS** [comment]
> There's no way that could have fixed anything, plus, I'm having the same issue on portainer, and I can't just add quotes into my configuration. There's gotta be an underlying issue here, I have 50000 opened up everywhere possible and no dice. I really don't understand what the issue is, running netstat within the docker container returns `tcp 0 0 :::50000 :::* LISTEN -`
> 
> Is this an IPv4 vs IPv6 issue? Literally pulling hair out of my head trying to figure this out.

are you using WSL2 + docker?

**Comment by t3rminalx** [comment]
You need to Port Forward port 50000 on your router to the ip of the machine that is running rtorrent.
