### ISSUE TITLE
ruTorrent webinterface shows older version

### ISSUE THREAD

**Issue by kellerman** [crazy-max/docker-rtorrent-rutorrent#47]
ruTorrent webinterface shows up as version 3.9 where it should be 3.10 instead. I tried **:latest**, **:edge** and: **3.10-0.9.8-0.13.8** images, but the webinterface still reports ruTorrent as 3.9
Can't understand whether I'm doing something wrong or is it a bug.

**Comment by crazy-max** [comment]
@kellerman Yes same behavior for me I will take a look.

**Comment by crazy-max** [comment]
@kellerman Novik/ruTorrent#2076

**Comment by crazy-max** [comment]
Should be fixed now
