### ISSUE TITLE
Add "Remove and Delete Data" option?

### ISSUE THREAD

**Issue by nation-wide** [crazy-max/docker-rtorrent-rutorrent#48]
I apologize if this is out of your scope, but I couldn't find how to add the option to remove data along with torrent. Please see this screenshot: [https://imgur.com/a/cH8HjuQ](https://imgur.com/a/cH8HjuQ) for reference.

If you know how to add this option, please consider it in the future versions.

Thank you for your work. This is by far the best rtorrent-rutorrent Docker image.

**Comment by nation-wide** [comment]
Ah, "Remove torrent" actually also deletes the data, not just the torrent. Okey, so that's good but maybe it could be two options...?

**Comment by crazy-max** [comment]
@nation-wide 

> Ah, "Remove torrent" actually also deletes the data

Yes that's it `Remove torrent` will also erase data. This is handled in the main `.rtorrent.rc`:

https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/9eaf55d9e609cbce5f4ce87baa53ab40639492da/rootfs/tpls/.rtorrent.rc#L65-L66

We could make it customizable through a new env var.

**Comment by crazy-max** [comment]
@nation-wide If you don't want data erased by rTorrent, remove the two lines I mentioned above and enable `erasedata` plugin: `RU_REMOVE_CORE_PLUGINS=httprpc`. Fyi, erase data with rTorrent is more efficient than ruTorrent `erasedata` plugin.
