### ISSUE TITLE
Custom auth_basic string

### ISSUE THREAD

**Issue by gwigz** [crazy-max/docker-rtorrent-rutorrent#5]
Just a little request if that's alright, because currently it's not very covert.

**Comment by crazy-max** [comment]
Basic auth is already available for XMLRPC  ruTorrent and WebDAV, see https://github.com/crazy-max/docker-rtorrent-rutorrent#notes

**Comment by gwigz** [comment]
Yes, however the value value for `auth_basic` is always set to “ruTorrent restricted access“ in the Nginx configs.

I was just hoping it’d be possible for an adjustment to be made to change that, without having to do it manually every release.

**Comment by crazy-max** [comment]
@gwigz Oh well, I didn't understand. We can do that of course.

**Comment by gwigz** [comment]
It works, thank you!

Worth adding a note that `@` and `!` would need escaping.
