### ISSUE TITLE
Question: How to override tracklabels pictures repository

### ISSUE THREAD

**Issue by the-lazy-fox** [crazy-max/docker-rtorrent-rutorrent#51]
Hi @crazy-max ,

I'm going through your image, create work you did!
While testing it, I just remember that all my current LSIO images have theses volumes mounted.
It's a template folder I made with all "original" labels and trackers icons which I have enriched over years.
```
      - /volume1/docker/rutorrent-template/tracklabels/labels:/app/rutorrent/plugins/tracklabels/labels:ro
      - /volume1/docker/rutorrent-template/tracklabels/trackers:/app/rutorrent/plugins/tracklabels/trackers:ro
```

I've identified in your image the location /var/www/rutorrent/plugins/tracklabels/labels|trackers which is the same one but I'm wondering if there is a better way to override these folders using your plugin override system (without touching the plugin itself)
If not, I will just mount the following
```
      - /volume1/docker/rutorrent-template/tracklabels/labels:/var/www/rutorrent/plugins/tracklabels/labels:ro
      - /volume1/docker/rutorrent-template/tracklabels/trackers:/var/www/rutorrent/plugins/tracklabels/trackers:ro
```

Thanks for your feedback

**Comment by crazy-max** [comment]
Hi @the-lazy-fox 

> using your plugin override system

Hum yes indeed we could  do that and override if already exists as an option. Today I do it like you:

```
- "./tracklabels:/var/www/rutorrent/plugins/tracklabels/labels"
```

**Comment by the-lazy-fox** [comment]
Thanks for your quick feedback!
As the plugin folder is composed by

- action.php
- init.js
- plugin.info
- tracklabels.cs
- labels
- trackers

It would be great if we could override (complete?) labels and trackers folders by just adding a assets in ./data/rutorrent/plugins/tracklabels/labels|trackers without having to take the whole plugin files (and not benefiting from updates, etc.)

Toughts? Is it complex to achieve?

Otherwise I will go with the good old way like mentionning before :)

**Comment by crazy-max** [comment]
@the-lazy-fox 

> Toughts? Is it complex to achieve?

Not really complex but it's adding technical debt and complexity about a specific plugin and I don't want this level of customization.

> Otherwise I will go with the good old way like mentionning before :)

Yeah go for it :)

**Comment by the-lazy-fox** [comment]
Thanks for the clarification, understandable 👍🏼
