### ISSUE TITLE
How to execute custom bash scripts inside the container?

### ISSUE THREAD

**Issue by the-lazy-fox** [crazy-max/docker-rtorrent-rutorrent#52]
Hi @crazy-max ,
On my previous r/rutorrent image, I was using several custom scripts like:

`method.set_key = event.download.finished,push_me,"execute=/scripts/pushover.sh,$d.name="`
or
`method.set_key = event.download.erased,remove_from_radarr,"execute=/scripts/remove_from_radarr.sh,$d.name=,$d.custom1="`

but it seems that bash is not part of the build?
Is there an alternative way to do so?

Thanks! 🚀

**Comment by crazy-max** [comment]
@the-lazy-fox You could convert to a POSIX shell script 😇

**Comment by crazy-max** [comment]
But all thing consider I think adding bash to this image seems legit for this kind of behavior.

**Comment by the-lazy-fox** [comment]
Yep, its pretty standard and a lot of people are using custom scripting inside rtorrent.

**Comment by crazy-max** [comment]
@the-lazy-fox Should be fixed now

**Comment by the-lazy-fox** [comment]
Thanks @crazy-max 
```/scripts # bash
ash: bash: not found```
Is there a specific way to call it? same result for ./myscript.sh

**Comment by crazy-max** [comment]
@the-lazy-fox `event.download.erased,remove_from_radarr,"execute=bash /scripts/remove_from_radarr.sh,`

**Comment by the-lazy-fox** [comment]
Yes but I was trying to execute it manually from inside the container first which is not working.
Command whereis bash returns nothing.

**Comment by crazy-max** [comment]
@the-lazy-fox Oh that's strange, I will take a look. Also can you post your script please?

**Comment by crazy-max** [comment]
@the-lazy-fox Works fine for me:

```
$ docker-compose exec rtorrent which bash
/bin/bash
$ docker run --rm -it --entrypoint '' crazymax/rtorrent-rutorrent:latest which bash
/bin/bash
```

Be sure to pull the latest image.

**Comment by the-lazy-fox** [comment]
Weird, image was the last one but had to down and restart, thought it was already done.
My bad.
Thanks 🚀
