### ISSUE TITLE
plugins directory aren't protected by password!

### ISSUE THREAD

**Issue by korni007** [crazy-max/docker-rtorrent-rutorrent#53]
When i enter to IP:8080/plugins/httprpc/action.php nginx doesn't ask me for user & password, but when i enter to IP:8080 i must enter login and password.
So... Authentication in rutorrent doesn't work fully. It is really security vulnerable for people who has rutorrent on vps,or other external service. Plugins folder are open for all unauthorized people from the web!

Are u fix this?

**Comment by crazy-max** [comment]
@korni007 

> When i enter to IP:8080/plugins/httprpc/action.php nginx doesn't ask me for user & password

There is no password protection for ruTorrent in this image. It's up to you to add it. For example with traefik:

```yaml
- "traefik.rutorrent.frontend.auth.basic.usersFile=/passwd-users"
```

**Comment by korni007** [comment]
Not? But on readme you write about htpasswd protection. Isn't the same?

**Comment by crazy-max** [comment]
@korni007 

> Not? But on readme you write about htpasswd protection. Isn't the same?

Let me see. Keep you in touch.

**Comment by crazy-max** [comment]
@korni007 Yep good catch there is an issue for php files only. Will fix that.

**Comment by crazy-max** [comment]
@korni007 Can you make a test with `crazymax/rtorrent-rutorrent:edge` please?

**Comment by korni007** [comment]
I've tested a few minutes ago. Brilliant! all works fine. Now nginx ask a username & password. thank u :)
