### ISSUE TITLE
Enhancement :  add a variable to customize the download folder

### ISSUE THREAD

**Issue by gauth-fr** [crazy-max/docker-rtorrent-rutorrent#54]
### Behaviour
The download foler is /downloads and can't be modified.

I can of course mount my folder where ever if want, but then there will be some inconsistency with what the container expect.

You can override the cfg.download & co in the .rtorrent.rc but then the webdav server won't point in the good place anymore.
So it would be good to have a variable (eg DOWNLOAD_DIR?), templatize the  .rtorrent.local and nginx webdav.conf  then do some sed in 03-config.sh :)

By the way why... ebcause i have many containers using this same directory (rtorrent, medusa, whatever) and when they talk together it's easier to have uniform paths :)

Thanks!

PS: i would help if ever i'd know to to make a push request...^^

#### Steps to reproduce this issue

1. It's not really a bug
2.

#### Expected behaviour

> to be able to customize the download directory thru a variable

**Comment by crazy-max** [comment]
@gauth-fr Same as https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/7#issuecomment-455901236

**Comment by gauth-fr** [comment]
it's what i'm doing but I understand your concerns about the change.
So i guess i'll stay like that and overload the variable in rtorrent.rc.
I'll also check with the devs of the other app (in this case medusa) if they can add like directory mapping to transform the path they get from rtorrent and rewrite it to match the medusa local path.

**Comment by crazy-max** [comment]
@gauth-fr 

> So i guess i'll stay like that and overload the variable in rtorrent.rc.

Sure feel free to customize your `.rtorrent.rc`.
