### ISSUE TITLE
Question: Is it possible to override the default download folder

### ISSUE THREAD

**Issue by the-lazy-fox** [crazy-max/docker-rtorrent-rutorrent#57]
Hi,

Currently the default download folder is /downloads/temp and then files are moved to /downloads/complete.
I'm preparing my migration from another image to this one and it's not working as expected, I'm not able to copy paste the session folder... all torrent resume path are automatically changed to /temp so I'm trying now to do my migration based on rutorrent autowatch recursive strategy. It works but stick to /downloads/temp but I would like to import them in /downloads/complete as they are already there and not to be downloaded.
I have folder and subfolders to seed my packs and episodes of my packs so I can't just update the path afterward, it will take hours, file per file.

directory = /downloads/complete in the rtorrent.rc file is not working neither.

Any advices?

Thanks

**Comment by crazy-max** [comment]
@See https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/7#issuecomment-455901236 and also https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/44

**Comment by the-lazy-fox** [comment]
Hello @crazy-max 
Thank for your feedback.
So If I do what you mentionned here: https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/44#issuecomment-750401556 
As torrent added recursively through the autowatch plugins will land in the client with the /complete root path?

**Comment by lilws** [comment]
@crazy-max Hi, I followed the #44 but these 2 folders (complete and temp) automatic create everytime container restart. Is there anyway to get risk of them completely?

**Comment by Darcidride** [comment]
> @crazy-max Hi, I followed the #44 but these 2 folders (complete and temp) automatic create everytime container restart. Is there anyway to get risk of them completely?

Hi, same here, do we have a way to delete them permanently ? (without rebuilding the image...) For now i'm using an external script to ensure they are deleted, but it's really weird :/

**Comment by lilws** [comment]
> Hi, same here, do we have a way to delete them permanently ? (without rebuilding the image...) For now i'm using an external script to ensure they are deleted, but it's really weird :/

It is not weird since owner don't want to get risk of it, It would be easy for someone to run this without many different config. So the best way I think of is, yes, running an external script to ensure those folders get removed every restart.
