### ISSUE TITLE
Question: Why removing EraseData plugin by default?

### ISSUE THREAD

**Issue by the-lazy-fox** [crazy-max/docker-rtorrent-rutorrent#58]
Hi @crazy-max,
Your feature to be able to remove any plugins from the image is a create idea, nevertheless I don't get the point of removing EraseData plugin.
Adding the removal of files on the "Remove" option instead is creating a lack of feature.
It's not possible anymore to remove a torrent while keeping the file.
Thanks for your feedback, I really don't want to rebuild a custom image for that purpose.
Best

**Comment by crazy-max** [comment]
@the-lazy-fox See https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/48#issuecomment-768161102

**Comment by the-lazy-fox** [comment]
Hi,

Thanks for it, I knew that.

Could you please provide a place where I can download "erasedata" plugins ready for your "override plugins" folder? I would like not to rebuild the entire images.

Thanks

**Comment by crazy-max** [comment]
@the-lazy-fox 

> Could you please provide a place where I can download "erasedata" plugins ready for your "override plugins" folder? I would like not to rebuild the entire images.

Already stipulated in https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/48#issuecomment-778831716:

> RU_REMOVE_CORE_PLUGINS=httprpc

Default for `RU_REMOVE_CORE_PLUGINS` is `erasedata,httprpc`.

**Comment by the-lazy-fox** [comment]
OK sorry, I tough it was build variables, my bad :)
