### ISSUE TITLE
Support unRAID container format

### ISSUE THREAD

**Issue by urbanracer34** [crazy-max/docker-rtorrent-rutorrent#59]
Good morning,

I use a piece of software called unRAID for my server. It is an OS that provides docker support. It is very popular.

I was wondering if maybe you could contribute your dockers to the official forum? https://forums.unraid.net/forum/47-docker-containers/

They also have a community plug-in for dockers called "Community Applications" that makes it a lot easier to set things up. 

Thanks! 

urbanracer34

**Comment by crazy-max** [comment]
Hi @urbanracer34,

Same as https://github.com/crazy-max/docker-nextcloud/issues/20#issuecomment-506553956. Sorry.
