### ISSUE TITLE
Include "pyrocore" into this image

### ISSUE THREAD

**Issue by RaymondSchnyder** [crazy-max/docker-rtorrent-rutorrent#6]
Hello,

I wanted to know if its possible to include the rtorrent utility "pyroscope" / "pyrocore" ( https://github.com/pyroscope/pyrocore ) in this, as it is a really good tool to manage rtorrent.

The documentation for pyrocore / pyroscope is here: https://pyrocore.readthedocs.io/en/latest/installation.html#option-1-installing-from-github

I, myself, am working on a fork with this included.
If i do any big progress, i will open a push request

**Comment by crazy-max** [comment]
Hi @RaymondSchnyder, I prefer to keep this image light as possible. I suggest to create an other Docker image for Pyrocore an plugin with this one using scgi protocol as I saw in the configuration : https://pyrocore.readthedocs.io/en/latest/setup.html
