### ISSUE TITLE
Modifying Your Image Help

### ISSUE THREAD

**Issue by XxAcielxX** [crazy-max/docker-rtorrent-rutorrent#65]
Hello again Crazy-max,

I hope it is allowed to make a modified container/image based on your `docker-rtorrent-rutorrent` with credits given ofcourse.

I did below patch to stop creation of `/downloads{completed,temp}` & changed default downloads location to `/downloads` in `.rtorrent.rc`.
```
RUN \
 echo "**** apply patches for /downloads ****" && \
 sed -ie '96s/themes [*\]/themes/' '/etc/cont-init.d/03-config.sh' && \
 sed -i '97,98d;310,311d' '/etc/cont-init.d/03-config.sh' && \
 sed -ie '5,23s/[*/]complete//' '/tpls/etc/nginx/conf.d/webdav.conf'
```
.rtorrent.rc
```
# Default download directory for torrents
directory.default.set = (cat,(cfg.download))

# Move finished (no need Autotools/Automove plugin on ruTorrent)
#method.insert = d.get_finished_dir, simple, "cat=$cfg.download_complete=,$d.custom1="
#method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
#method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,$d.get_finished_dir="
```

Everything works, but I can't figure out why `{completed,temp}` are still being created. I hope you can guide me on this.

Another thing I have noticed is that in `/var/www/rutorrent/conf/config.php`, you have set `$topDirectory = '/';`. Don't you think this is a security issue as user can navigate up to `root` directory of the container in rutorrent web-ui. 

You can see my changes at [xxacielxx/rutorrent](https://github.com/XxAcielxX/rutorrent). 

**Regards**

**Comment by lilws** [comment]
I want to stop creating of these 2 folders too. So quick way is I bing the 03 config and comment out those lines.

**Comment by XxAcielxX** [comment]
> I want to stop creating of these 2 folders too. So quick way is I bind the 03 config and comment out those lines.

This in the first thing I did in 03-config.sh
```
 sed -ie '96s/themes [*\]/themes/' '/etc/cont-init.d/03-config.sh' && \
 sed -i '97,98d;310,311d' '/etc/cont-init.d/03-config.sh' && \
```

**Comment by lilws** [comment]
> > I want to stop creating of these 2 folders too. So quick way is I bind the 03 config and comment out those lines.
> 
> This in the first thing I did in 03-config.sh
> 
> ```
> sed -ie '96s/themes [*\]/themes/' '/etc/cont-init.d/03-config.sh' && \
> sed -i '97,98d;310,311d' '/etc/cont-init.d/03-config.sh'
> ```

Did you mount 03-config.sh into docker volume? This file will be reset everytime docker-compose up if not bind it to a file in host. So is your script running before 03-config.sh or after?

**Comment by XxAcielxX** [comment]
> > > I want to stop creating of these 2 folders too. So quick way is I bind the 03 config and comment out those lines.
> > 
> > 
> > This in the first thing I did in 03-config.sh
> > ```
> > sed -ie '96s/themes [*\]/themes/' '/etc/cont-init.d/03-config.sh' && \
> > sed -i '97,98d;310,311d' '/etc/cont-init.d/03-config.sh'
> > ```
> 
> Did you mount 03-config.sh into docker volume? This file will be reset everytime docker-compose up if not bind it to a file in host. So is your script running before 03-config.sh or after?

I have made my own image based on crazy-max one. I'm running the patch before the the container starts.

I have solved my own problem haha. I'm suppose to use `sed -i -e`, not `-ie` combined. The latter created a backup of `03-config.sh` into `03-config.she` which was being executed after with the non-patched file.

My issue is solved now. @lilws you can find my image at [xxacielxx/rutorrent](https://github.com/XxAcielxX/rutorrent)
