### ISSUE TITLE
I tried to install filemanager plugins but it fails with error "FILE MANAGER: Failed to get directory contents"

### ISSUE THREAD

**Issue by lilws** [crazy-max/docker-rtorrent-rutorrent#66]
When using rutorrent, I want to install some third-party plugins and filemanger is the main package for other thing to work. But in alpine linux it caused error above in rutorrent log.

Fix at the moment I found in https://github.com/nelu/rutorrent-thirdparty-plugins/issues/10#issuecomment-301342888
by running this line in bash `apk add --no-cache findutils`
Atm, to save time when restart container, I bind /etc/cont-init.d/ to a location and add that line to 03-config.sh.

**Comment by lilws** [comment]
> Hello @lilws Did you manage to make it work now? On my side adding it to the plugins folder makes the start of the image impossible. Is there any dependancies? Thank you

If you read my post correctly, adding plugins folder is not enough, you should add findutils too.

BTW, I'm not using linux atm so I changed to qBittorrent for now.

**Comment by the-lazy-fox** [comment]
Hello @lilws 
Thank you, I did😢
I've added `- ./cont-init.d/03-config.sh:/etc/cont-init.d/03-config.sh` this mount in my docker compose file containing:
```#!/bin/bash
apk add --no-cache findutils```
It makes the app to not start and fill logs with:
`nginx: [emerg] mkdir() "/usr/lib/nginx/client_body_temp" failed (13: Permission denied) rtorrent: Failed to parse command line option: Could not open option file: /etc/rtorrent/.rtlocal.rc`
Did you run through the same? Is there anything wrong in the setup?
Thank you for your help!

**Comment by lilws** [comment]
If you're using this docker long enough. You should know that it is very strict in adding something different to its init scripts. The error stated that permission error. You should scroll back and see if it works. Rather than that I don't think that line you added cause too much trouble like that.

**Comment by the-lazy-fox** [comment]
Sorry @lilws I'm not as wise as you are...
As mentionned above, "It makes the app to not start and fill logs".
Impossible to start with this line you recommended.
Any advice?
Thank you very much.

**Comment by crazy-max** [comment]
> If you read my post correctly, adding plugins folder is not enough, you should add findutils too.

`findutils` is already available in the image: https://github.com/crazy-max/docker-rtorrent-rutorrent/pull/67

**Comment by the-lazy-fox** [comment]
Hello @crazy-max 
Thanks for letting me know!
Therefore, is there anyway to make this plugin to work from your knowledge?  Or it gets back to https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/178 ?
Thank you!
