### ISSUE TITLE
Feature request: ports customization

### ISSUE THREAD

**Issue by 73fb7vbb74c3** [crazy-max/docker-rtorrent-rutorrent#69]
Hi @crazy-max. It would be really helpful if it allows to change ports with environment variables. I wish I could run rtorrent with "--network host" to avoid docker NAT performance loss but some ports are already in use. Adding this feature would also make it easier to run multiple instances with the host network. Thank you very much!

**Comment by crazy-max** [comment]
@73fb7vbb74c3 Sure could be done with #55

**Comment by 73fb7vbb74c3** [comment]
@crazy-max Thanks a lot! That would be very nice!

**Comment by crazy-max** [comment]
Should be fixed with #73
