### ISSUE TITLE
Start rutorrent plugins with rtorrent without start webui first

### ISSUE THREAD

**Issue by lilws** [crazy-max/docker-rtorrent-rutorrent#71]
I found this on [Novik rutorrent wiki](https://github.com/Novik/ruTorrent/wiki/Plugins#starting-plugins-with-rtorrent) but as I tried to add it to .rtorrent.rc, it is not working.

`execute2 = {sh,-c,/usr/bin/php /var/www/ruTorrent/php/initplugins.php username &}`

There is some plugins like seedingtime, throttle, it will not work if I don't open webui of rutorrent for it to init first.
For example 1: seedingtime add 2 columns "Added" and "Finished", if webui don't start first, it will not write any data to these 2 columns.
For example 2: I'm using Set channel to limit download or upload speed of a single torrent, after the container restart, these limit is not apply until webui start.

Can you take a look into this?

Thank you.

**Comment by crazy-max** [comment]
@lilws 

Looks like a good enhancement to me yes.

**Comment by lilws** [comment]
I tried to test this command inside container with:
`sh -c /usr/bin/php /var/www/ruTorrent/php/initplugins.php lilw &`
but it is not working.

But I tried with other rutorrent docker and it works. For example I tested with romancin/rutorrent. He had this execute in rtorrent.rc but it is not working as describe in Novik wiki until I run that command inside a container.

**Comment by lilws** [comment]
after a while I figured out that in container bash I can run something like this:

```
su rtorrent
/usr/bin/php /var/www/rutorrent/php/initplugins.php lilw &
```

but I'm still can't figured out how to run this automatically.

**Comment by jnsn** [comment]
The username should be `rtorrent`, as that is the one mapped from inside the container to the one that has write permissions to the `/data` folder, not `lilw`.

Adding the following command to the `.rtlocal.rc` or the `.rtorrent.rc` file should do the trick:
```
execute2 = {sh,-c,/usr/bin/php7 /var/www/rutorrent/php/initplugins.php rtorrent &}
```

**Comment by lilws** [comment]
I didn't check with .rtlocal.rc but with .rtorrent.rc I did but it not work. 

I use lilw because I read in the wiki it supposed to be the web username which I authenticated to access rutorrent.
