### ISSUE TITLE
Custom port not working

### ISSUE THREAD

**Issue by EVOTk** [crazy-max/docker-rtorrent-rutorrent#75]
### Behaviour
The objective is to have 2 rutorrent instances on the same bridge network.

#### Steps to reproduce this issue

1. I have a container with the ports by default
2. I add a container with "custom" ports
3. Container with modified ports not working

#### Expected behaviour

> 2 rutorrent instances on the same bridge network.

#### Actual behaviour

> Container with modified ports not working
The logs indicates that the container tries to communicate with the ports by default, and does not take custom ports

### Configuration

* Docker version (type `docker --version`) : 18.09.8
* Docker compose version if applicable (type `docker-compose --version`) :  1.24.0
* Platform (Debian 9, Ubuntu 18.04, ...) : DSM 6.2.3
* System info (type `uname -a`) : Linux 4.4.59+ #25426 SMP PREEMPT Tue Nov 24 17:18:27 CST 2020 x86_64 GNU/Linux synology_apollolake_918+
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

Container with modified ports > 
![2021-04-12 23_13_32-Portainer ](https://user-images.githubusercontent.com/45015615/114463478-c4b55900-9be4-11eb-9ec7-f45acdaa5851.png)

### Logs

Container with modified ports > 
[_rutorrent_logs.txt](https://github.com/crazy-max/docker-rtorrent-rutorrent/files/6299864/_rutorrent_logs.txt)

**Comment by crazy-max** [comment]
@EVOTk Healthcheck ports are now handled dynamically for `XMLRPC_PORT`, `RUTORRENT_PORT` and `WEBDAV_PORT`. (e.g. if you define `RUTORRENT_PORT=8080`, port `8081` will be reserved). So be careful with port affectation.

**Comment by EVOTk** [comment]
@crazy-max 
Thank you for the precision, I just validated the operation at the moment!
Thank you so much !
