### ISSUE TITLE
Question: want to setup Htpasswd but having issues with it

### ISSUE THREAD

**Issue by MichiDe** [crazy-max/docker-rtorrent-rutorrent#77]
Hi,
Want to setup Htpasswd but having issues with it

If i edit the files with an note editor and add username password then rutorrent is asking for a username and password but then it fails.

When using the command: docker run --rm -it httpd:2.4-alpine htpasswd -Bbn <username> <password> >> $(pwd)/passwd/webdav.htpasswd
Then get the reply -ash: syntax error near unexpected token `<'
If change the line <username> <password> for test test then it tells me no such file or directory.

Im running docker from my synology nas and ssh into the nas to perform this action

**Comment by cfw34683** [comment]
while the container is down. so docker-compose down. use 
`docker run --rm -it httpd:2.4-alpine htpasswd -Bbn USER PASS >> $(pwd)/passwd/webdav.htpasswd`
bring container up
use `docker exec -it CONTAINERID bash` once in do `cd passwd/` then `vi webdav.htpasswd`
copy the info line that has your username and pass(as salt) and paste it into the other .htpasswd files in the same folder

**Comment by MichiDe** [comment]
thanks now working but had to remove and reinstall using docker-compose wasn't using that before

**Comment by cfw34683** [comment]
if this is fixed please mark as solved to close this issue

**Comment by FloydKulis** [comment]
> thanks now working but had to remove and reinstall using docker-compose wasn't using that before

Can you please tell me step by step how you did it. I used the cfw34683 post and generated a password, but unfortunately when I run the rtorrent GUI, I still don't need to enter the password.
