### ISSUE TITLE
Auto dl irssi and XML-RPC socket

### ISSUE THREAD

**Issue by describe19** [crazy-max/docker-rtorrent-rutorrent#79]
Hi I'm trying to use autodl irssi on the host machine (without the rutorrent plugin for now) and the add to rtorrent action uses the XML-RPC socket (8000) I've modified my docker-compose to publish the XML-RPC port and configured autodl to send to 127.0.0.1:8000, however I get the following error from autodl when it tries to add to rtorrent:

`error: XmlRpc::_onDataReceived: Invalid XML-RPC response (not XML)`

Any idea why this is? Thanks.

Edit: Is it related the nginx basic auth? The contents of the files in the passwd directory are currently empty - I have not configured any auth. But perhaps whatever is being sent over port 8000 is not what autodl is expecting. If someone could help me understand the issue I'd be grateful.

**Comment by ImjuzCY** [comment]
I also tried exposing the `scgi.socket` file to the host and to another container with `autodl-irssi`, but `autodl-irssi` can't seem to add torrents via it. I've tried `chmod 777` on the socket file, doesn't help. Flood can see the download queue through it, but also can't add torrents via the socket file.

**Comment by NZLostboy** [comment]
I am having the same issue trying to get Sonarr to connect to XML-RPC.

**Comment by NZLostboy** [comment]
As a note, I tried the Docker image "romancin" provides using the same configuration and didn't have the issue. I will try to spend some time debugging it later.

**Comment by crazy-max** [comment]
Works fine for me:

```shell
$ docker-compose exec rutorrent curl --data '<?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>system.library_version</methodName></methodCall>' http://127.0.0.1:8000
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<params>
<param><value><string>0.13.8</string></value></param>
</params>
</methodResponse>
```

**Comment by NZLostboy** [comment]
@crazy-max The latest image seems to be working fine, but it was definitely not working when I tried it previously. As always thank you for your work.
@describe19 Do you have time to test this again with the latest image?

**Comment by 420tushar** [comment]
Hey 

> @crazy-max The latest image seems to be working fine, but it was definitely not working when I tried it previously. As always thank you for your work. @describe19 Do you have time to test this again with the latest image?

Hi can you tell how to setup sonarr with this i am unable to do that i am using sonarr in docker contianer and very confused what to put in the rtorrent config in sonarr to make it work it was easy for qbit but i want to setup for rtorrent

**Comment by neo-neo1** [comment]
Can someone share how they got SCGI to connect? I'm up against a wall
