### ISSUE TITLE
 myip.opendns.com is depreciated for finding wanip

### ISSUE THREAD

**Issue by ttocszed00** [crazy-max/docker-rtorrent-rutorrent#80]
#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

> output external ip address into the variable ${wanip}

#### Actual behaviour

> nothing,  myip.opendns.com doesn't exist anymore

### Configuration

* Docker version (type `docker --version`) : Docker version 20.10.6, build 370c289
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.29.1, build c34c88b2
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 20.04
* System info (type `uname -a`) : Linux dockerhost 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

rtorrent_rutorrent:
      image: crazymax/rtorrent-rutorrent:latest
      container_name: rtorrent_rutorrent
      environment:
        - WAN_IP=XXX.XXX.XXX.XXX
        - TZ=Tokyo/Japan
        - PUID=1000
        - GUID=1000
      volumes:
        - "/mnt/docker/rtorrent_rutorrent/:/data:rw"
        - "/plex-media/torrents/:/downloads:rw"
        - "/mnt/docker/rtorrent_rutorrent/passwd/:/passwd:rw"
      networks:
        - torrent-network
      ports:
        - "50000:50000"

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-72-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 64
 Total Memory: 125.8GiB
 Name: dockerhost
 ID: Q5TZ:KG66:ZAYS:Z2JZ:AIZI:OK7V:7L5J:OZPK:TLFI:72AY:66DX:AE3L
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
```

**Comment by crazy-max** [comment]
@ttocszed00

> myip.opendns.com is depreciated for finding wanip

AFAIK it's not deprecated. What is your source about that? If you have trouble using it you can specify your public IP yourself with `WAN_IP` env var.
