### ISSUE TITLE
Can't mount custom content inside /var/www/rutorrent

### ISSUE THREAD

**Issue by the-lazy-fox** [crazy-max/docker-rtorrent-rutorrent#83]
#### Steps to reproduce this issue

1.Mount volumes like 
```
- /home/thelazyfox/docker/rutorrent/tracklabels/labels:/var/www/rutorrent/plugins/tracklabels/labels:ro
- /home/thelazyfox/docker/rutorrent/tracklabels/trackers:/var/www/rutorrent/plugins/tracklabels/trackers:ro
```

#### Expected behaviour

Custom label and trackers icons, I followed your recommendation from https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/51#issuecomment-791685555 

#### Actual behaviour

Content is not accessible due to permissions. Every content around is nobody:nogroup but the mounted content is the user:group launching the container.

### Configuration

-   Docker version: 20.10.6
-   Docker compose version if applicable: 1.29.1
-   Platform (Debian 9, Ubuntu 18.04, ...) : Debian 10

**Comment by lilws** [comment]
In this image, the behavior is it will delete all contents inside /var/www/rutorrent/plugins and replace with content you put in /data/rutorrent/plugins. I suggest you to read the instruction again.

**Comment by the-lazy-fox** [comment]
Hello @lilws 
I’m following the recommendation of @crazy-max. Please read carefully my message. I’m not talking about importing a new plugin or a modified version of one. 
I’m talking about overriding an existing folder as he suggested.

**Comment by lilws** [comment]
Hello @the-lazy-fox 
I apologize. I don't know why crazy-max offer this, but it is kind of messed up every permission for me so far.

Why don't you just use the simple instructions, put all these plugins inside /data/rutorrent/plugins/tracklabels? 
In /etc/cont-init.d/03-config.sh I found that everytime this container start, it will try to delete all things inside /var/www/rutorrent/plugins/ and replace with new contents you put inside /data/rutorrent/plugins. So mount it into your volume is not a good idea as I see.

This image is so different from LSIO from post-running expect so I don't think you can configure it as you liked. I did changed from couple of images to this and find a huge problems that my data need to adapt. I've been struggled it couple days before make it running as I want.

**Comment by crazy-max** [comment]
@the-lazy-fox 

> ```
> - /home/thelazyfox/docker/rutorrent/tracklabels/labels:/var/www/rutorrent/plugins/tracklabels/labels:ro
> - /home/thelazyfox/docker/rutorrent/tracklabels/trackers:/var/www/rutorrent/plugins/tracklabels/trackers:ro
> ```

I don't think tracklabels are intended to work with subfolders.

**Comment by the-lazy-fox** [comment]
Issue disappeared while using the same compose file. Didn't understood why.
