### ISSUE TITLE
Question: parameters for running the container on a NAS with lower end CPU

### ISSUE THREAD

**Issue by maisun** [crazy-max/docker-rtorrent-rutorrent#84]
Hi,
Thanks for the docker image! I have configured it to run on my QNAP NAS with a weak J4125 CPU, and would like to understand how to tune the container:

1)  I started Docker container with the following parameters from the example without knowing what and why they are needed? Could those options have any impact on the performance of other services on the NAS? 
--ulimit nproc=65535 \
--ulimit nofile=32000:40000 \
2) What is the recommended settings for memory? I currently configured 4GB memory but it uses all. I only have 16G in total so can't assign more memory. Any suggestion?

Any input is appreciated!

**Comment by lilws** [comment]
You should read performance tunning in rtorrent rakshasa wiki.

This is base on peers and torrent contents. If your torrent have thousands of peers and the torrent content a lot of files in it. You probably need to limit max file open and max peer connected in rtorrent.rc.

**Comment by maisun** [comment]
> You should read performance tunning in rtorrent rakshasa wiki.
> 
> This is base on peers and torrent contents. If your torrent have thousands of peers and the torrent content a lot of files in it. You probably need to limit max file open and max peer connected in rtorrent.rc.

Tried that - I found the problem was high read io when seeding with upload 1-3MB the disk read is always above 50MB. I saw many have this issue and since rTorrent is not maintained for a long time I decided to give qBitTorrent a try.

**Comment by lilws** [comment]
> > You should read performance tunning in rtorrent rakshasa wiki.
> > This is base on peers and torrent contents. If your torrent have thousands of peers and the torrent content a lot of files in it. You probably need to limit max file open and max peer connected in rtorrent.rc.
> 
> Tried that - I found the problem was high read io when seeding with upload 1-3MB the disk read is always above 50MB. I saw many have this issue and since rTorrent is not maintained for a long time I decided to give qBitTorrent a try.

I did that too, but lately found that qbittorrent is a monster eating all of resource, especially CPU. With only 200 torrents and 5 of them have more than 2000 peers. My CPU freezed in every 3 days. rtorrent manage CPU performance better then qbit, I think.

**Comment by maisun** [comment]
> > > You should read performance tunning in rtorrent rakshasa wiki.
> > > This is base on peers and torrent contents. If your torrent have thousands of peers and the torrent content a lot of files in it. You probably need to limit max file open and max peer connected in rtorrent.rc.
> > 
> > 
> > Tried that - I found the problem was high read io when seeding with upload 1-3MB the disk read is always above 50MB. I saw many have this issue and since rTorrent is not maintained for a long time I decided to give qBitTorrent a try.
> 
> I did that too, but lately found that qbittorrent is a monster eating all of resource, especially CPU. With only 200 torrents and 5 of them have more than 2000 peers. My CPU freezed in every 3 days. rtorrent manage CPU performance better then qbit, I think.

I run both rTorrent/ruTorrent and Qbittorrent in docker and so far I haven't notice any CPU issue with Qbittorrent. I will try to add more torrents to it. I do find with Qbittorrent it also reads 10MB from HDD even though it only uploads 1-2MB, it is better than rTorrent but I'm still not very happy. The disk IO is the bottleneck of my NAS and I'd definitely like to minimise it if possible. I have tried the following with rTorrent without luck:
1) Disable preload
2) Assign more memory (8G)

**Comment by maisun** [comment]
> > > > You should read performance tunning in rtorrent rakshasa wiki.
> > > > This is base on peers and torrent contents. If your torrent have thousands of peers and the torrent content a lot of files in it. You probably need to limit max file open and max peer connected in rtorrent.rc.
> > > 
> > > 
> > > Tried that - I found the problem was high read io when seeding with upload 1-3MB the disk read is always above 50MB. I saw many have this issue and since rTorrent is not maintained for a long time I decided to give qBitTorrent a try.
> > 
> > 
> > I did that too, but lately found that qbittorrent is a monster eating all of resource, especially CPU. With only 200 torrents and 5 of them have more than 2000 peers. My CPU freezed in every 3 days. rtorrent manage CPU performance better then qbit, I think.
> 
> I run both rTorrent/ruTorrent and Qbittorrent in docker and so far I haven't notice any CPU issue with Qbittorrent. I will try to add more torrents to it. I do find with Qbittorrent it also reads 10MB from HDD even though it only uploads 1-2MB, it is better than rTorrent but I'm still not very happy. The disk IO is the bottleneck of my NAS and I'd definitely like to minimise it if possible. I have tried the following with rTorrent without luck:
> 
> 1. Disable preload
> 2. Assign more memory (8G)

Tried both without luck. Switch to qbittorent still experience similar problem but reading is now below 10MB so much better. Qbittorrent also seems to allow stop gracefully plus better features I think I will settle with it for now.

**Comment by crazy-max** [comment]
Suggest to open an issue on rTorrent repo.
