### ISSUE TITLE
rTorrent will not start 

### ISSUE THREAD

**Issue by slamanna212** [crazy-max/docker-rtorrent-rutorrent#85]
### Behaviour
rTorrent fails to start on start of container, log is filled with errors

`
rtorrent: Invalid/unknown option flag "-i". See rtorrent -h for more information.
rtorrent: option requires an argument: i
rtorrent: Invalid/unknown option flag "-i". See rtorrent -h for more information.
rtorrent: option requires an argument: i
`

#### Steps to reproduce this issue

1. Pull container 
2. Start Container

#### Expected behaviour

rtorrent should start 

#### Actual behaviour
This is the error that is put in the docker logs

`
rtorrent: Invalid/unknown option flag "-i". See rtorrent -h for more information.
rtorrent: option requires an argument: i
rtorrent: Invalid/unknown option flag "-i". See rtorrent -h for more information.
rtorrent: option requires an argument: i
`
### Configuration

* Docker version (type `docker --version`) : Docker version 19.03.14, build 5eb3275
* Docker compose version if applicable (type `docker-compose --version`) : N/A
* Platform (Debian 9, Ubuntu 18.04, ...) : unRaid 6.9.3
* System info (type `uname -a`) : Linux Columbia 5.10.19-Unraid #1 SMP Sat Feb 27 08:00:30 PST 2021 x86_64 Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz GenuineIntel GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
root@Columbia:~# docker info
Client:
 Debug Mode: false

Server:
 Containers: 12
  Running: 8
  Paused: 0
  Stopped: 4
 Images: 13
 Server Version: 19.03.14
 Storage Driver: btrfs
  Build Version: Btrfs v4.20.1 
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea765aba0d05254012b0b9e595e995c09186427f
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.19-Unraid
 Operating System: Slackware 14.2 x86_64 (post 14.2 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 23.48GiB
 Name: Columbia
 ID: ZMQB:MQJF:4MAM:FRP5:2IXQ:QPAD:TKKJ:6JX2:DWYS:ASXE:7I36:IWWA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### Logs

```
> Container logs (set LOG_LEVEL to debug if applicable)
```

**Comment by slamanna212** [comment]
I was able to find a fix, but i can not find where it is in the git repo to submit a pull request. 

Workaround:
- attach a shell to the running container
- navigate to `/var/run/s6/services/rtorrent`
- open the file named `run` with vi
- Line 6, remove the -i at the end of that line
- press escape then type :wq to save and quit vi
- rtorrent will start

**Comment by crazy-max** [comment]
@slamanna212 What command do you use to run the container? Please include all necessary configuration files: `docker-compose.yml`, `.env`, ...

**Comment by slamanna212** [comment]
@crazy-max my bad! Its all done through the unraid WebUI so ill include a screenshot of that. It is 2 screenshots and there is overlap

https://slama.vip/i/p8Cr.png

https://slama.vip/i/puDS.png

**Comment by crazy-max** [comment]
@slamanna212 

> my bad! Its all done through the unraid WebUI so ill include a screenshot of that. It is 2 screenshots and there is overlap

Sorry I don't bring support for UnRaid. See #59

> Line 6, remove the -i at the end of that line

But if [this line](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/master/rootfs/etc/cont-init.d/04-create-services.sh#L28) is your issue then something looks wrong with the `WAN_IP` env var (I guess it's empty).

Can you give me the output of `env|sort` inside the container? (redacted)

**Comment by slamanna212** [comment]
@crazy-max  in reguards to #59 , I dont need that. It runs just run on unraid and thats an un-needed extra step. Not the issue here. 

I do not have a WAN IP set in the container, it did not cause an issue before. My WAN IP changes though so i am hesitant to hardcode it into an ENV.

**Comment by crazy-max** [comment]
@slamanna212 

> I do not have a WAN IP set in the container, it did not cause an issue before. My WAN IP changes though so i am hesitant to hardcode it into an ENV.

`WAN_IP` is [automatically resolved](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/aeba27c1c73d85c8af8852b6603d9a40395c9ad6/rootfs/etc/cont-init.d/03-config.sh#L3) if not provided. So I guess the following command does not work for you:

```shell
dig +short myip.opendns.com @resolver1.opendns.com)
````

Can you give me the output?

**Comment by slamanna212** [comment]
That is odd, I get an error!

`
dig: parse of /etc/resolv.conf failed
`

**Comment by slamanna212** [comment]
the file has contents that i can read as well, 

`
bash-5.0# cat resolv.conf 
search North11th
nameserver 127.0.0.11
nameserver fe80::b6fb:e4ff:fe25:a2b1%br0
options ndots:0
`

**Comment by crazy-max** [comment]
The second nameserver is invalid.

**Comment by slamanna212** [comment]
@crazy-max literally just realized that and came here to mention it. Fixing that lets me dig
