### ISSUE TITLE
The list of all trackers is not loaded correctly

### ISSUE THREAD

**Issue by the-lazy-fox** [crazy-max/docker-rtorrent-rutorrent#86]
#### Steps to reproduce this issue

1. Open rutorrent with several torrents from several trackers
2. Check the filter section "trackers"

#### Expected behaviour

> All unique tracker should be in the list with a counter next to it + total volume summ

#### Actual behaviour

> The list is empty and trackers will show up ONLY when I manually click on one torrent --> tracker added in the list but counter = 1
> Then if I select another torrent it completed the filter section
> Etc.

### Configuration

* Docker version (type `docker --version`) : Docker version 20.10.6, build 370c289
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.29.1, build c34c88b2 
* Platform (Debian 9, Ubuntu 18.04, ...) : Debian 10
* System info (type `uname -a`) : Linux docker-host 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Comment by the-lazy-fox** [comment]
No issues in my client with 1000 and 2000 torrents.
I have this issue only for client with 4000+ torrents.

**Comment by crazy-max** [comment]
Don't think that's an issue with the Docker image itself. Suggest to open an issue on [ruTorrent](https://github.com/Novik/ruTorrent).

**Comment by the-lazy-fox** [comment]
Thanks.
For the sake of tracking: https://github.com/Novik/ruTorrent/issues/2171

**Comment by TrimmingFool** [comment]
> I'm running docker on crazy-max images so I will not be able to do so. [https://github.com/Novik/ruTorrent/issues/2171](https://github.com/Novik/ruTorrent/issues/2171)

@the-lazy-fox you could try building your own image for the time being. Something like:
```dockerfile
FROM crazymax/rtorrent-rutorrent:latest
RUN curl https://patch-diff.githubusercontent.com/raw/Novik/ruTorrent/pull/2170.diff | patch -d /var/www/rutorrent -fnp1
```
`docker build . -t custom-rtorrent-rutorrent`

**Comment by the-lazy-fox** [comment]
@TrimmingFool 

```
Step 2/2 : RUN curl https://patch-diff.githubusercontent.com/raw/Novik/ruTorrent/pull/2170.diff | patch -d /var/www/rutorrent -fnp1
 ---> Running in 59be8ada52fe
/bin/sh: patch: not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1022    0  1022    0     0    201      0 --:--:--  0:00:05 --:--:--   251
curl: (23) Failed writing body (0 != 1022)
The command '/bin/sh -c curl https://patch-diff.githubusercontent.com/raw/Novik/ruTorrent/pull/2170.diff | patch -d /var/www/rutorrent -fnp1' returned a non-zero code: 127
```

whereis patch --> patch: /usr/bin/patch

**Comment by the-lazy-fox** [comment]
The issue remains exactly the same 😞

**Comment by the-lazy-fox** [comment]
Hello @crazy-max 
Accordingly to the other comments I found, it might be fix with the last version of rtorrent master.
https://github.com/rakshasa/rtorrent/pull/905 
Could you please have a look?
Thanks a lot

**Comment by TrimmingFool** [comment]
> The issue remains exactly the same

That's somewhat disappointing. Possible causes I could think of:

1. Browser cache prevents update
2. Patch is not correctly applied ( Since I did not test building/running the image )
3. Your original issue is different from mine

**Comment by the-lazy-fox** [comment]
```
FROM crazymax/rtorrent-rutorrent:latest
RUN apk --update --no-cache add curl git subversion tar tree xz patch
RUN curl https://patch-diff.githubusercontent.com/raw/Novik/ruTorrent/pull/2170.diff | patch -d /var/www/rutorrent -fup1
```

```
docker build . -t custom-rtorrent-rutorrent
```

Doesn't work neither. Could you please post your command?
Thanks!

**Comment by crazy-max** [comment]
@the-lazy-fox 

> Hello @crazy-max
> Accordingly to the other comments I found, it might be fix with the last version of rtorrent master.
> [rakshasa/rtorrent#905](https://github.com/rakshasa/rtorrent/pull/905)
> Could you please have a look?
> Thanks a lot

Thanks for your feedback but can't endorse unstable releases for this image. We'll have to wait for a new release of rTorrent. You can [build the image yourself](https://github.com/crazy-max/docker-rtorrent-rutorrent#build-locally) if you want with the latest changes from rTorrent repo.

**Comment by TrimmingFool** [comment]
> Doesn't work neither. Could you please post your command?

@the-lazy-fox I edited my previous message with the command I used. 
You could also try:
1. Disable 'httprpc' plugin or remove its cache from the /data volume.
 `docker exec -t rm -r /data/rutorrent/share/users/rtorrent/settings/httprpc` 
(httprpc uses php/settings.php and php/xmlrpc.php)
2. Clear the browser cache (this is only relevant if httprpc is disabled such that js/rtorrent.js would be used)
3. Disable other plugins that might override normal xmlrpc behavior

**Comment by the-lazy-fox** [comment]
Great, it works! Thanks @TrimmingFool 

Now we just need to wait for rtorrent to release a new stable release which can be integrated in this image...
In the meanwhile, I will use this.

```
FROM crazymax/rtorrent-rutorrent:latest
RUN apk --update --no-cache add curl git subversion tar tree xz patch
RUN apk --update --no-cache add patch && \
    curl https://patch-diff.githubusercontent.com/raw/Novik/ruTorrent/pull/2170.diff | \
    patch -d /var/www/rutorrent -fup1
```

`docker build . -t custom-rtorrent-rutorrent`

**Comment by TrimmingFool** [comment]
@the-lazy-fox You're welcome! Was it necessary to clear the httprpc cache?

**Comment by the-lazy-fox** [comment]
Not at all. Just restarted the container with the new image and it was ok.

**Comment by CMclarty** [comment]
Just to add - I had the same issue, and removing httprpc from the excluded plugins solved the issues. I am sure it was placed there by default for a reason, but from my testing it has introduced no further errors yet.
