### ISSUE TITLE
option requires an argument: i

### ISSUE THREAD

**Issue by mabushey** [crazy-max/docker-rtorrent-rutorrent#88]
### Configuration

* Docker version (type `docker --version`) : Docker version 20.10.6, build 370c28948e
* Docker compose version if applicable (type `docker-compose --version`) :  docker-compose version 1.29.1, build unknown
* Platform (Debian 9, Ubuntu 18.04, ...) :  Arch (running docker so irrelevant)
* System info (type `uname -a`) : Linux corwin 5.11.13-arch1-1 #1 SMP PREEMPT Sat, 10 Apr 2021 20:47:14 +0000 x86_64 GNU/Linux (running docker so irrelevant)
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

I must have done a docker pull, my current Image ID is 3aed83e38f70

docker logs -f rtorrent
```
...
rtorrent: option requires an argument: i
rtorrent: Invalid/unknown option flag "-i". See rtorrent -h for more information.
rtorrent: option requires an argument: i
rtorrent: Invalid/unknown option flag "-i". See rtorrent -h for more information.
rtorrent: option requires an argument: i
rtorrent: Invalid/unknown option flag "-i". See rtorrent -h for more information.
- - - [11/May/2021:09:48:50 -0600] "GET /plugins/diskspace/action.php?_=1620747551463 HTTP/1.1" 200 47 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
```

The logs are filled with this.

**Comment by TemhAAhmeT** [comment]
That" i" is variable WAN_IP.

**Comment by mabushey** [comment]
That makes some sense. Thanks!
