### ISSUE TITLE
Changes to the rtlocalrc file

### ISSUE THREAD

**Issue by caioortiz** [crazy-max/docker-rtorrent-rutorrent#95]
#### Steps to reproduce this issue

Hi,

I made changes to the .rtlocal.rc file, but they are not saved.
(https://github.com/crazy-max/docker-rtorrent-rutorrent#boostrap-config-rtlocalrc)

Steps:
_git clone https://github.com/crazy-max/docker-rtorrent-rutorrent.git_
_cd docker-rtorrent-rutorrent_
I edit the file in _docker-rtorrent-rutorrent/rootfs/tpls/etc/rtorrent/.rtlocal.rc_
Make the _docker buildx bake image_
Then do the _docker tag_ and _docker push_
I run the _docker run_ with the modified docker image

Access ruTorrent, but changes don't happen
For example, I add limit on the download / upload:
_Global upload and download rate in KiB, '0' for unlimited ('download_rate', 'upload_rate')
throttle.global_up.max_rate.set_kb = 1536
throttle.global_down.max_rate.set_kb = 2560_
Accessing with the docker exec, the .rtlocal.rc file has the modification, however opening it in ruTorrent, it did not apply, there is no limit.

Could you help me what am I doing wrong?

Thank you very much for providing this docker image and sorry for the English.

### Configuration

* Docker version (type `docker --version`) : 20.10.6
* Docker compose version if applicable (type `docker-compose --version`) :  1.26.2
* Platform (Debian 9, Ubuntu 18.04, ...) : Debian 10
* System info (type `uname -a`) : Linux debian 4.19.0-16-amd64 1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Comment by ImjuzCY** [comment]
What changes did you make? Some configs are overwritten at container start up by `rootfs/etc/cont-init.d/03-config.sh`, so you might get better results from just letting `.rtlocal.rc` be and adding lines to `.rtorrent.rc` to override the config.

**Comment by caioortiz** [comment]
Hi,

I need to add global upload and download.

```
# Global upload and download rate in KiB. "0" for unlimited
throttle.global_down.max_rate.set_kb = 1024
throttle.global_up.max_rate.set_kb = 1024
```

I didn't find elements for global upload and download rate in .rtorrent.rc, so I would have to rebuild the image, right? 
https://github.com/crazy-max/docker-rtorrent-rutorrent#boostrap-config-rtlocalrc

How do I rebuild the image with this change?

**Comment by ImjuzCY** [comment]
These options are in the default `.rtorrent.rc` line 13 and 14. That's why it's not applied even when you add them in `.rtlocal.rc`. Values in `.rtorrent.rc` overrides values in `.rtlocal.rc`. 

All you need to do is just edit the values in `/data/rtorrent/.rtorrent.rc`. The files should be editable from the host after first run if you have mounted `/data`. You shouldn't have to edit the source and rebuild for this.

**Comment by caioortiz** [comment]
Perfect, I changed to `/data/rtorrent/.rtorrent.rc` and restarted the container.

Working now! Thanks a lot for the help.
