### ISSUE TITLE
WAN_IP with non-static ip address

### ISSUE THREAD

**Issue by vgogh4v** [crazy-max/docker-rtorrent-rutorrent#99]
Hi, I've started to use this great image and want to let it work 24/7.
I'm wondering about WAN_IP.. my ip address is dynamic and changing every few days~. i'm afraid to be blocked on private trackers for faking my ip.

The WAN_IP variable is currently empty for me, so it resolved automatically. Do the client will change the IP also automatically?
or if the ip got changed and the container is up, the ip that will be reported to the trackers will remain the old one?

what should I do?

Thanks!

**Comment by crazy-max** [comment]
Should be fixed with #96
